(function(g){var window=this;'use strict';var N5=function(a,b){return b?a.captionsInitialState:"CAPTIONS_INITIAL_STATE_UNKNOWN"},OIa=function(a){return g.hI(a)?g.V(a.experiments,"web_player_caption_language_preference_stickiness_duration"):0},O5=function(a){var b={languageCode:a.languageCode,
languageName:a.languageName,displayName:g.BI(a),kind:a.kind,name:a.name,id:a.id,is_servable:a.j,is_default:a.isDefault,is_translateable:a.isTranslateable,vss_id:a.vssId};a.xtags&&(b.xtags=a.xtags);a.captionId&&(b.captionId=a.captionId);a.translationLanguage&&(b.translationLanguage=a.translationLanguage);return b},P5=function(a){return a.translationLanguage?a.translationLanguage.languageCode:a.languageCode},PIa=function(a,b){var c=new g.AI;
c.languageCode=a.languageCode;c.languageName=a.languageName;c.name=a.name;c.kind=a.kind;c.isDefault=!1;c.j=a.j;c.isTranslateable=a.isTranslateable;c.vssId=a.vssId;c.url=a.url;c.translationLanguage=b;a.xtags&&(c.xtags=a.xtags);a.captionId&&(c.captionId=a.captionId);return c},QIa=function(a,b){var c,d,e;
return g.D(function(f){if(1==f.j)return c=a+"|"+b,g.z(f,g.vs(),2);if(3!=f.j){d=f.u;if(!d)throw g.Gr("gct");return g.z(f,g.iJ(d),3)}e=f.u;return f.return(e.get("captions",c))})},RIa=function(a,b,c){QIa(a,b).then(function(d){d&&c(d.trackData,new g.AI(d.metadata))})},SIa=function(a){var b=b||0;
return function(){return a.apply(this,Array.prototype.slice.call(arguments,0,b))}},Q5=function(a,b,c){g.F.call(this);
this.j=null;this.C=!1;this.F=a;this.D=c;this.u=b||window;this.B=(0,g.Ra)(this.SM,this)},R5=function(a){a.isActive()||a.start()},TIa=function(a){a=a.u;
return a.requestAnimationFrame||a.webkitRequestAnimationFrame||a.mozRequestAnimationFrame||a.oRequestAnimationFrame||a.msRequestAnimationFrame||null},UIa=function(a){a=a.u;
return a.cancelAnimationFrame||a.cancelRequestAnimationFrame||a.webkitCancelRequestAnimationFrame||a.mozCancelRequestAnimationFrame||a.oCancelRequestAnimationFrame||a.msCancelRequestAnimationFrame||null},S5=function(){return g.rx("yt-player-caption-display-settings")},VIa=function(){this.u=[];
this.j=[]},T5=function(a,b){return b?a.j.concat(a.u):a.j},U5=function(a,b){switch(b.kind){case "asr":WIa(b,a.u);
break;default:WIa(b,a.j)}},WIa=function(a,b){g.ib(b,function(c){return a.equals(c)})||b.push(a)},V5=function(a){g.F.call(this);
this.J=a;this.u=new VIa;this.C=[]},W5=function(a,b,c){V5.call(this,a);
this.audioTrack=c;this.j=null;this.B=!1;this.C=b.HB;this.B="shortspage"===g.qK(b)},X5=function(){this.segments=[]},XIa=function(a,b){var c=g.xb(a.segments,b);
0<=c||0>c&&1===(-c-1)%2||(c=-c-1,0<c&&1===b-a.segments[c-1]&&c<a.segments.length&&1===a.segments[c]-b?(g.ob(a.segments,c),g.ob(a.segments,c-1)):0<c&&1===b-a.segments[c-1]?a.segments[c-1]=b:c<a.segments.length&&1===a.segments[c]-b?a.segments[c]=b:(g.ub(a.segments,c,0,b),g.ub(a.segments,c+1,0,b)))},Y5=function(a,b,c,d,e,f){g.F.call(this);
this.policy=a;this.player=b;this.V=c;this.K=d;this.D=e;this.T=f;this.C=new X5;this.F=-1;this.B=this.u=this.j=null;this.G=new g.El(this.PJ,1E3,this);this.events=new g.BF(this);g.H(this,this.G);g.H(this,this.events);this.events.oa(b,"SEEK_COMPLETE",this.pz);this.pz();this.PJ()},YIa=function(a){return a.j&&a.j.C?a.j.C+a.player.Hc()<a.player.getCurrentTime():!1},ZIa=function(a,b){var c=g.CE(b,a.policy,{}).Wd(),d={format:"RAW",
withCredentials:!0};a.policy.Na&&(d.method="POST",d.postBody=b.Ko()||(0,g.mQ)([120,0]));a.D&&(d.responseType="arraybuffer");a.B=g.Rp(c,d,3,100).then(function(e){a:{e=e.xhr;a.isDisposed();if(a.u){var f=!(a.D?e.response:e.responseText)||400<=e.status,h=g.fG(e);if(h){e=g.CE(a.u,a.policy,{});a.u.Cj(e,h);ZIa(a,a.u);break a}f?a.player.Y("capfail",{status:e.status}):(a.player.zg().dg("fcb_r"),h=a.u.Ja[0].xa,null!=a.K&&a.F!==h&&(f=a.u.Ja[0],a.D?a.K(e.response,1E3*(f.startTime+a.player.Hc())):a.K(e.responseText,
1E3*(f.startTime+a.player.Hc())),a.F=h))}a.u=null;a.B=null}}).Oh(function(e){a.u=null;
a.B=null;var f;a.player.Y("capfail",{status:null==(f=e.xhr)?void 0:f.status})});
a.u=b;XIa(a.C,a.u.Ja[0].xa)},Z5=function(a,b){V5.call(this,b.X());
this.j=a;this.N=b;this.B=null;this.D=!1;this.F=g.jI(this.N.X())&&!this.j.isManifestless},aJa=function(a,b){var c=[],d;
for(d in a.j.j)if(a.j.j.hasOwnProperty(d)){var e=a.j.j[d];if(g.RL(e,b||null)){var f=e.info.id,h=f,l="."+f,m="",n="",p="";if(e=e.info.captionTrack)f=e.languageCode,h=e.displayName,l=e.vssId,m=e.kind,a.N.X().I("html5_expose_xtags_through_caption_track")&&(n=e.xtags),p=e.id;else{e=f;var q=g.Dva.get(e);null==q&&(q=$Ia[e]||$Ia[e.replace(/-/g,"_")],g.Dva.set(e,q));h=q||h}c.push(new g.AI({id:d,languageCode:f,languageName:h,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:l,kind:m,xtags:n,captionId:p}))}}return c},
bJa=function(a,b){return null!=b&&b in a.j.j?a.j.j[b]:null},cJa=function(a,b,c){var d=[],e;
for(e in a.j.j)if(a.j.j.hasOwnProperty(e)){var f=a.j.j[e];if(g.RL(f,c||null)){var h=f.info.captionTrack;h&&h.languageCode===b&&d.push(f)}}return d.length?d[0]:null},$5=function(a,b,c,d,e){V5.call(this,a);
this.videoId=c;this.D=e;this.F={};this.j=null;a=d||g.Zo(b).hl||"";a=a.split("_").join("-");this.B=g.ap(b,{hl:a})},b6=function(a,b,c,d){b=void 0===b?!1:b;
d=void 0===d?!1:d;g.Bx.call(this);this.G=!1;this.C=new g.gw(this);this.D=this.F=null;this.B=this.u=!1;g.H(this,this.C);this.target=a;this.j=b;this.K=c||a;this.G=d;b&&(g.kl&&this.target.setAttribute("draggable","true"),this.target.style.touchAction="none");a6(this)},c6=function(a){g.jw(a.C,!a.j)},a6=function(a){a.D=null;
a.F=null;a.oa(d6("over"),a.bp);a.oa("touchstart",a.MA);a.j&&a.oa(d6("down"),a.LP)},dJa=function(a,b){for(var c=0;c<b.changedTouches.length;c++){var d=b.changedTouches[c];
if(d.identifier===a.F)return d}return null},d6=function(a){return window.navigator.msPointerEnabled?"MSPointer"+a.charAt(0).toUpperCase()+a.substr(1):"mouse"+a},e6=function(a){if(!eJa.test(a))throw Error("'"+a+"' is not a valid hex color");
4==a.length&&(a=a.replace(fJa,"#$1$1$2$2$3$3"));a=a.toLowerCase();a=parseInt(a.slice(1),16);return[a>>16,a>>8&255,a&255]},gJa=function(){if(!g.pe)return!1;
try{return new ActiveXObject("MSXML2.DOMDocument"),!0}catch(a){return!1}},iJa=function(a){if("undefined"!=typeof DOMParser){var b=new DOMParser;
a=g.Bd(a);return b.parseFromString(g.Ad(a),"application/xml")}if(hJa){b=new ActiveXObject("MSXML2.DOMDocument");b.resolveExternals=!1;b.validateOnParse=!1;try{b.setProperty("ProhibitDTD",!0),b.setProperty("MaxXMLSize",2048),b.setProperty("MaxElementDepth",256)}catch(c){}b.loadXML(a);return b}throw Error("Your browser does not support loading xml documents");},jJa=function(){var a=void 0;
a=void 0===a?{}:a;var b="suggest_correction"in f6?f6.suggest_correction:"Edit caption";b=b||"";var c={},d;for(d in a){c.Ws=d;var e=function(f){return function(){return String(a[f.Ws])}}(c);
b=b.replace(new RegExp("\\$\\{"+c.Ws+"\\}","gi"),e);b=b.replace(new RegExp("\\$"+c.Ws,"gi"),e);c={Ws:c.Ws}}return b},g6=function(a,b,c,d,e,f,h,l,m,n){var p={};
Object.assign(p,b);Object.assign(p,a.params);Object.assign(p,c);var q={};Object.assign(q,b.Uc);a.params.Uc&&Object.assign(q,a.params.Uc);Object.assign(q,c.Uc);p.Uc=q;var r=1===p.kf,t=[{S:"span",ra:"captions-text",Ka:{style:"word-wrap: normal; display: block;"}}],u,x,A;(l=l.Va("caption_edit_on_hover")&&(null==(u=n.getVideoData().getPlayerResponse())?void 0:null==(x=u.captions)?void 0:null==(A=x.playerCaptionsTracklistRenderer)?void 0:A.openTranscriptCommand))&&t.unshift({S:"button",ra:"caption-edit",
Ka:{tabindex:"0","aria-label":jJa()},Da:[{S:"svg",Ka:{fill:"#e3e3e3",height:"100%",viewBox:"5 5 38 38",width:"100%"},Da:[{S:"path",Ka:{d:"M9 39h2.2l24.25-24.25-1.1-1.1-1.1-1.1L9 36.8Zm-3 3v-6.4L35.4 6.2q.85-.85 2.12-.82 1.27.02 2.12.87L41.8 8.4q.85.85.85 2.1t-.85 2.1L12.4 42Zm33.5-31.55L37.45 8.4Zm-4.05 4.3-1.1-1.1-1.1-1.1 2.2 2.2Z"}}]}]});g.oL.call(this,{S:"div",ra:"caption-window",Ka:{id:"caption-window-"+a.id,dir:r?"rtl":"ltr",tabindex:"0",lang:p.lang},Da:t});var B=this;this.G=[];this.Ba=!1;this.u=
a;this.Fa=this.Aa=null;this.playerWidth=f;this.playerHeight=h;this.K=null;this.maxWidth=.96*f;this.Xa=.96*h;this.j=p;this.Mc=c;this.ea=b;this.D=this.Qa("captions-text");this.Vb=""!==this.D.style.getPropertyValue("box-decoration-break")||""!==this.D.style.getPropertyValue("-webkit-box-decoration-break");this.Ha=kJa(d,e,f,h);this.zc=m;l&&(this.F=this.Qa("caption-edit"),this.oa(this.F,"click",function(){B.zc()}));
this.type=0;this.sb=this.Ha*lJa(q);a=new b6(this.element,!0);g.H(this,a);a.subscribe("dragstart",this.AQ,this);a.subscribe("dragmove",this.zQ,this);a.subscribe("dragend",this.yQ,this);this.Cb=this.vb=this.vc=this.Ib=0;a="";this.j.windowOpacity&&(a=e6(this.j.windowColor),a="rgba("+a[0]+","+a[1]+","+a[2]+","+this.j.windowOpacity+")");b={"background-color":a,display:!1===this.j.isVisible?"none":"","text-align":mJa[this.j.textAlign]};this.Vb&&(b["border-radius"]=a?this.sb/8+"px":"");(this.C=2===this.u.params.kf||
3===this.u.params.kf)&&nJa(this,this.element);g.il(this.element,b);switch(this.j.lh){case 0:case 1:case 2:g.Ml(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.Ml(this.element,"ytp-caption-window-bottom")}},nJa=function(a,b){var c="vertical-rl";
1===a.j.DF&&(c="vertical-lr");g.pe&&(c="vertical-lr"===c?"tb-lr":"tb-rl");g.il(b,"-o-writing-mode",c);g.il(b,"-webkit-writing-mode",c);g.il(b,"writing-mode",c);g.il(b,"text-orientation","upright");g.Ml(b,"ytp-vertical-caption");3===a.u.params.kf&&(g.il(b,"text-orientation",""),g.il(b,"transform","rotate(180deg)"))},lJa=function(a){var b=1+.25*(a.fontSizeIncrement||0);
if(0===a.offset||2===a.offset)b*=.8;return b},oJa=function(a,b){var c={},d=b.background?b.background:a.j.Uc.background;
if(null!=b.backgroundOpacity||b.background){var e=null!=b.backgroundOpacity?b.backgroundOpacity:a.j.Uc.backgroundOpacity;d=e6(d);c.background="rgba("+d[0]+","+d[1]+","+d[2]+","+e+")";a.Vb&&(c["box-decoration-break"]="clone",c["border-radius"]=a.sb/8+"px")}if(null!=b.fontSizeIncrement||null!=b.offset)c["font-size"]=a.Ha*lJa(b)+"px";d=1;e=b.color||a.j.Uc.color;if(b.color||null!=b.textOpacity)e=e6(e),d=null==b.textOpacity?a.j.Uc.textOpacity:b.textOpacity,e="rgba("+e[0]+","+e[1]+","+e[2]+","+d+")",c.color=
e,c.fill=e;var f=b.charEdgeStyle;0===f&&(f=void 0);if(f){e="rgba(34, 34, 34, "+d+")";var h="rgba(204, 204, 204, "+d+")";b.IB&&(h=e=b.IB);var l=a.Ha/16/2,m=Math.max(l,1),n=Math.max(2*l,1),p=Math.max(3*l,1),q=Math.max(5*l,1);d=[];switch(f){case 4:for(;p<=q;p+=l)d.push(n+"px "+n+"px "+p+"px "+e);break;case 1:n=2<=window.devicePixelRatio?.5:1;for(f=m;f<=p;f+=n)d.push(f+"px "+f+"px "+e);break;case 2:d.push(m+"px "+m+"px "+h);d.push("-"+m+"px -"+m+"px "+e);break;case 3:for(p=0;5>p;p++)d.push("0 0 "+n+"px "+
e)}c["text-shadow"]=d.join(", ")}e="";switch(b.fontFamily){case 1:e='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:e='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:e='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:e='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:e='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:e=g.eq()?'"Carrois Gothic SC", sans-serif-smallcaps':
'"Arial Unicode Ms", Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:e='"YouTube Noto", Roboto, "Arial Unicode Ms", Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}e&&(c["font-family"]=e);e=b.offset;null==e&&(e=a.j.Uc.offset);switch(e){case 0:c["vertical-align"]="sub";break;case 2:c["vertical-align"]="super"}7===b.fontFamily&&(c["font-variant"]="small-caps");b.bold&&(c["font-weight"]="bold");b.italic&&(c["font-style"]="italic");b.underline&&(c["text-decoration"]=
"underline");b.hP&&(c.visibility="hidden");1===b.oJ&&a.C&&(c["text-combine-upright"]="all",c["text-orientation"]="mixed",e=g.RO||g.Er,3===a.u.params.kf?c.transform=e?"rotate(90deg)":"rotate(180deg)":e&&(c.transform="rotate(-90deg)"));if(1===b.Oi||2===b.Oi||3===b.Oi||4===b.Oi||5===b.Oi)if(g.RO)c["font-weight"]="bold";else switch(c["text-emphasis-style"]="filled circle",c["text-emphasis-color"]="currentcolor",c["webkit-text-emphasis"]="filled circle",b.Oi){case 4:case 3:c["text-emphasis-position"]=
"under left";c["webkit-text-emphasis-position"]="under left";break;case 5:case 2:c["text-emphasis-position"]="over right",c["webkit-text-emphasis-position"]="over right"}return c},pJa=function(a){a.K=g.ee("SPAN");
g.il(a.K,{display:"block"});g.Ml(a.K,"caption-visual-line");a.D.appendChild(a.K)},qJa=function(a,b){var c=g.ee("SPAN");
g.il(c,{display:"inline-block","white-space":"pre-wrap"});g.il(c,oJa(a,b));c.classList.add("ytp-caption-segment");a.K.appendChild(c);c.previousElementSibling&&(g.il(c.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.il(c,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return c},rJa=function(a,b,c){a.Ba=a.Ba||!!c;
var d={};Object.assign(d,a.j.Uc);Object.assign(d,c||b.j);Object.assign(d,a.Mc.Uc);(c=!a.K)&&pJa(a);for(var e=a.Aa&&a.Fa&&g.Cc(d,a.Fa)?a.Aa:qJa(a,d),f="string"===typeof b.text,h=f?b.text.split("\n"):[b.text],l=0;l<h.length;l++){var m=0<l||!b.append,n=h[l];m&&!c?(pJa(a),e=qJa(a,d)):m&&c&&(c=!1);n&&(e.appendChild(f?g.ge(n):n),f||"RUBY"!==n.tagName||4!==n.childElementCount||g.RO||!g.ml(n.children[2],"text-emphasis")||(m=a.C?"padding-right":"padding-top",g.ml(n.children[2],"text-emphasis-position")&&(m=
a.C?"padding-left":"padding-bottom"),g.kl?g.il(e,m,"1em"):g.il(e,m,"0.5em")))}a.Fa=d;a.Aa=e;a.G.push(b)},kJa=function(a,b,c,d){var e=b/360*16;
b>=a&&(a=640,d>1.3*c&&(a=480),e=c/a*16);return e},h6=function(a,b,c,d){V5.call(this,a);
this.videoData=b;this.audioTrack=c;this.Ea=d;this.C=b.HB},i6=function(a,b,c,d,e,f,h,l,m,n){g6.call(this,a,b,c,d,e,f,h,l,m,n);
this.type=1},j6=function(a,b,c,d,e,f,h,l,m,n){g6.call(this,a,b,c,d,e,f,h,l,m,n);
var p=this;this.type=2;this.T=[];this.ma=this.V=this.Na=0;this.ya=NaN;this.Qb=0;this.Rc=null;this.Wa=new g.El(this.ZQ,433,this);this.F&&(n.au(this.F,this,167342),this.oa(this.F,"click",function(){n.Yo(p.F)}),a=new b6(this.element,!0),g.H(this,a),a.subscribe("hoverstart",function(){n.Wf(p.F,!0)},this));
g.Ml(this.element,"ytp-caption-window-rollup");g.H(this,this.Wa);g.il(this.element,"overflow","hidden")},sJa=function(a,b){if(!b)return"";
a.C&&1!==a.u.params.DF&&(b*=-1);return"translate"+(a.C?"X":"Y")+"("+b+"px)"},tJa=function(a){a.T=Array.from(document.getElementsByClassName("caption-visual-line"));
for(var b=a.u.params.rl,c=0,d=0,e=a.T.length-1;c<b&&-1<e;){var f=a.T[e];d+=a.C?f.offsetWidth:f.offsetHeight;c++;e--}a.T.length<b&&(d*=b/a.T.length);a.V=d;b=Math;c=b.max;isNaN(a.ya)&&((d=a.j.Yl)?(e=g.ee("SPAN"),g.ne(e,"\u2013".repeat(d)),g.il(e,oJa(a,a.j.Uc)),a.D.appendChild(e),a.ya=e.offsetWidth,a.D.removeChild(e)):a.ya=0);d=a.D;a.ma=c.call(b,a.ya,a.Qb,(a.C?d.offsetHeight:d.offsetWidth)+1)},uJa=function(a,b){tJa(a);
var c=a.T.reduce(function(e,f){return(a.C?f.offsetWidth:f.offsetHeight)+e},0);
c=a.V-c;if(c!==a.Na){var d=0<c&&0===a.Na;b||isNaN(c)||d||(g.Ml(a.element,"ytp-rollup-mode"),g.Fl(a.Wa));g.il(a.D,"transform",sJa(a,c));a.Na=c}tJa(a)},k6=function(a,b,c,d,e,f,h){f=void 0===f?!1:f;
h=void 0===h?null:h;g.IK.call(this,a,a+b,{priority:c,namespace:"captions"});this.windowId=d;this.text=e;this.append=f;this.j=h},l6=function(a,b,c,d,e){g.IK.call(this,a,a+b,{priority:c,
namespace:"captions"});this.id=d;this.params=e;this.j=[]},vJa=function(a){var b="_"+m6++;
return new l6(0,0x8000000000000,0,b,a)},xJa=function(a,b,c,d,e,f,h){var l=f[0],m=h[l.getAttribute("p")];
if(1===m.Od){var n=f[1],p=f[2];f=f[3];l.getAttribute("t");n.getAttribute("t");p.getAttribute("t");f.getAttribute("t");l.getAttribute("p");n.getAttribute("p");f.getAttribute("p");h=h[p.getAttribute("p")];l=wJa(l.textContent,n.textContent,p.textContent,f.textContent,h);return new k6(a,b,e,c,l,d,m)}switch(m.Od){case 9:case 10:m.Oi=1;break;case 11:m.Oi=2;break;case 12:m.Oi=3;break;case 13:m.Oi=4;break;case 14:m.Oi=5}return new k6(a,b,e,c,l.textContent||"",d,m)},wJa=function(a,b,c,d,e){var f=g.eq(),h=
f?g.ee("DIV"):g.ee("RUBY"),l=g.ee("SPAN");
l.textContent=a;h.appendChild(l);a=f?g.ee("DIV"):g.ee("RP");a.textContent=b;h.appendChild(a);b=f?g.ee("DIV"):g.ee("RT");b.textContent=c;h.appendChild(b);c=e.Od;if(10===c||11===c||12===c||13===c||14===c)if(g.il(b,"text-emphasis-style","filled circle"),g.il(b,"text-emphasis-color","currentcolor"),g.il(b,"webkit-text-emphasis","filled circle"),11===e.Od||13===e.Od)g.il(b,"webkit-text-emphasis-position","under left"),g.il(b,"text-emphasis-position","under left");c=!0;if(4===e.Od||7===e.Od||12===e.Od||
14===e.Od)g.il(h,"ruby-position","over"),g.il(h,"-webkit-ruby-position","before");else if(5===e.Od||6===e.Od||11===e.Od||13===e.Od)g.il(h,"ruby-position","under"),g.il(h,"-webkit-ruby-position","after"),c=!1;e=f?g.ee("DIV"):g.ee("RP");e.textContent=d;h.appendChild(e);f&&(d=c,g.il(h,{display:"inline-block",position:"relative"}),f=h.firstElementChild.nextElementSibling,g.il(f,"display","none"),f=f.nextElementSibling,g.il(f,{"font-size":"0.5em","line-height":"1.2em","text-align":"center",position:"absolute",
left:"50%",transform:"translateX(-50%)",width:"400%"}),g.il(h.lastElementChild,"display","none"),d?(g.il(h,"padding-top","0.6em"),g.il(f,"top","0")):(g.il(h,"padding-bottom","0.6em"),g.il(f,"bottom","0")));return h},n6=function(){g.F.apply(this,arguments)},o6=function(a){n6.call(this);
this.C=a;this.pens={};this.K={};this.T={};this.D="_"+m6++;this.G={};this.B=this.j=null;this.F=!0},p6=function(a,b){a=a.getAttribute(b);
if(null!=a)return Number(a)},q6=function(a,b){a=a.getAttribute(b);
if(null!=a)return"1"===a},r6=function(a,b){a=p6(a,b);
return void 0!==a?a:null},t6=function(a,b){a=a.getAttribute(b);
if(null!=a)return s6.test(a),a},yJa=function(a,b){var c={},d=b.getAttribute("ws");
Object.assign(c,d?a.T[d]:a.C);a=r6(b,"mh");null!=a&&(c.Gr=a);a=r6(b,"ju");null!=a&&(c.textAlign=a);a=r6(b,"pd");null!=a&&(c.kf=a);a=r6(b,"sd");null!=a&&(c.DF=a);a=t6(b,"wfc");null!=a&&(c.windowColor=a);b=p6(b,"wfo");void 0!==b&&(c.windowOpacity=b/255);return c},zJa=function(a,b){var c={},d=b.getAttribute("wp");
d&&Object.assign(c,a.K[d]);a=r6(b,"ap");null!=a&&(c.lh=a);a=p6(b,"cc");null!=a&&(c.Yl=a);a=p6(b,"ah");null!=a&&(c.Cg=a);a=p6(b,"rc");null!=a&&(c.rl=a);b=p6(b,"av");null!=b&&(c.Pi=b);return c},AJa=function(a,b,c,d){var e={};
Object.assign(e,zJa(a,b));Object.assign(e,yJa(a,b));d?g.Cc(e,a.C)?(d=a.D,e=a.C):d="_"+m6++:d=b.getAttribute("id")||"_"+m6++;a=p6(b,"t")+c;b=p6(b,"d")||0x8000000000000;if(2===e.kf||3===e.kf)c=e.rl,e.rl=e.Yl,e.Yl=c;return new l6(a,b,0,d,e)},u6=function(a){n6.call(this);
this.F=a;this.j=new Map;this.C=new Map;this.D=new Map;this.B=new Map},v6=function(a){a=g.Ed(Math.round(a),0,16777215).toString(16).toUpperCase();
return"#000000".substr(0,7-a.length)+a},BJa=function(a,b,c,d,e){0===d&&(d=0x8000000000000);
var f={};b.wpWinPosId&&Object.assign(f,a.C.get(b.wpWinPosId));b.wsWinStyleId&&Object.assign(f,a.D.get(b.wsWinStyleId));a=b.rcRowCount;void 0!==a&&(f.rl=a);b=b.ccColCount;void 0!==b&&(f.Yl=b);if(2===f.kf||3===f.kf)b=f.rl,f.rl=f.Yl,f.Yl=b;return new l6(c,d,0,e,f)},x6=function(){this.B=this.time=this.mode=this.u=0;
this.C=new w6(this);this.D=new w6(this);this.j=[];this.clear()},DJa=function(a,b,c){if(255===a&&255===b||!a&&!b)return{Yn:a,
Vl:b,result:0};a=CJa[a];b=CJa[b];if(a&128){var d;if(d=!(b&128))d=b,d=c.isValid()&&c.Vl===d;if(d)return{Yn:a,Vl:b,result:1}}else if(b&128&&1<=a&&31>=a)return{Yn:a,Vl:b,result:2};return{Yn:a,Vl:b,result:3}},FJa=function(a,b,c,d){255===b&&255===c||!b&&!c?(45===++a.B&&a.reset(),a.C.u.clear(),a.D.u.clear()):(a.B=0,EJa(a.C,b,c,d))},GJa=function(a,b){a.j.sort(function(e,f){var h=e.time-f.time;
return 0===h?e.order-f.order:h});
for(var c=g.v(a.j),d=c.next();!d.done;d=c.next())d=d.value,a.time=d.time,0===d.type?FJa(a,d.UH,d.VH,b):1===d.type&&a.u&496&&EJa(a.D,d.UH,d.VH,b);a.j.length=0},y6=function(){this.type=0},z6=function(){this.state=this.Vl=this.Yn=0},HJa=function(){this.timestamp=this.j=0},A6=function(a){this.D=a;
this.B=[];this.j=this.u=this.row=0;this.style=new y6;for(a=this.C=0;15>=a;a++){this.B[a]=[];for(var b=0;32>=b;b++)this.B[a][b]=new HJa}},B6=function(a,b){if(3===a.style.type){for(var c=0,d=0,e=a.D.time+0,f="",h="",l=e,m=1;15>=m;++m){for(var n=!1,p=d?d:1;32>=p;++p){var q=a.B[m][p];
if(0!==q.j){0===c&&(c=m,d=p);n=String.fromCharCode(q.j);var r=q.timestamp;r<e&&(e=r);q.timestamp=l;h&&(f+=h,h="");f+=n;n=!0}if((0===q.j||32===p)&&n){h="\n";break}else if(d&&!n)break}if(c&&!n)break}f&&b.C(c,d,e,l,f)}else for(d=c=0,f=e=a.D.time+0,h=1;15>=h;++h)for(l="",m=1;32>=m;++m)if(p=a.B[h][m],q=p.j,0!==q&&(0===c&&(c=h,d=m),n=String.fromCharCode(q),r=p.timestamp,r<=e&&(e=r),l+=n,p.reset()),32===m||0===q)l&&b.C(c,d,e,f,l),e=f,l="",d=c=0},MJa=function(a,b){switch(a){case 0:return IJa[(b&127)-32];
case 1:return JJa[b&15];case 2:return KJa[b&31];case 3:return LJa[b&31]}return 0},C6=function(a){return a.B[a.row][a.u]},D6=function(a,b,c){2<=b&&1<a.u&&(--a.u,C6(a).j=0);
var d=C6(a);d.timestamp=a.D.time+0;d.j=MJa(b,c);32>a.u&&a.u++},NJa=function(a,b,c,d){for(var e=0;e<d;e++)for(var f=0;32>=f;f++){var h=a.B[b+e][f],l=a.B[c+e][f];
h.j=l.j;h.timestamp=l.timestamp}},E6=function(a,b,c){for(var d=0;d<c;d++)for(var e=0;32>=e;e++)a.B[b+d][e].reset()},F6=function(a){a.row=0<a.j?a.j:1;
a.u=1;E6(a,0,15)},G6=function(a){this.B=a;
this.D=0;this.style=new y6;this.F=new A6(this.B);this.G=new A6(this.B);this.text=new A6(this.B);this.u=this.F;this.C=this.G;this.j=this.u},H6=function(a,b,c){var d=a.u,e=!1;
switch(a.style.get()){case 4:case 1:case 2:4===a.style.get()&&0<d.j||(B6(d,c),F6(a.u),F6(a.C),d.row=15,d.j=b,e=!0)}a.style.set(3);a.j=d;a.j.style=a.style;a.B.mode=1<<d.C;e?d.u=1:d.j!==b&&(d.j>b?(B6(d,c),E6(d,d.row-d.j,b)):d.row<b&&(b=d.j),d.j=b)},OJa=function(a){a.style.set(1);
a.j=a.C;a.j.j=0;a.j.style=a.style;a.B.mode=1<<a.j.C},PJa=function(a){a.style.set(4);
a.j=a.text;a.j.style=a.style;a.B.mode=1<<a.j.C},w6=function(a){this.j=a;
this.D=0;this.B=new G6(this.j);this.F=new G6(this.j);this.u=new z6;this.C=this.B},EJa=function(a,b,c,d){a.u.update();
b=DJa(b,c,a.u);switch(b.result){case 0:return;case 1:case 2:return}var e=b.Yn;c=b.Vl;if(32<=e||!e)a.j.mode&a.j.u&&(b=e,b&128&&(b=127),c&128&&(c=127),a=a.C.j,b&96&&D6(a,0,b),c&96&&D6(a,0,c),0!==b&&0!==c&&3===a.style.type&&B6(a,d));else if(e&16)a:if(!a.u.matches(e,c)&&(b=a.u,b.Yn=e,b.Vl=c,b.state=2,b=e&8?a.F:a.B,a.C=b,a.j.mode=1<<(a.D<<2)+(b.D<<1)+(4===b.style.type?1:0),(a.j.mode|1<<(a.D<<2)+(b.D<<1)+(4!==b.style.type?1:0))&a.j.u))if(c&64){d=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(e&7)<<1|c>>5&1];
a=c&16?4*((c&14)>>1):0;c=b.j;switch(b.style.get()){case 4:d=c.row;break;case 3:if(d!==c.row){if(d<c.j&&(d=c.j,d===c.row))break;var f=1+c.row-c.j,h=1+d-c.j;NJa(c,h,f,c.j);b=f;e=c.j;h<f?(f=h+e-f,0<f&&(b+=f,e-=f)):(f=f+e-h,0<f&&(e-=f));E6(c,b,e)}}c.row=d;c.u=a+1}else switch(e&7){case 1:switch(c&112){case 32:D6(b.j,0,32);break a;case 48:57===c?(d=b.j,C6(d).j=0,32>d.u&&d.u++):D6(b.j,1,c&15)}break;case 2:c&32&&D6(b.j,2,c&31);break;case 3:c&32&&D6(b.j,3,c&31);break;case 4:case 5:if(32<=c&&47>=c)switch(c){case 32:OJa(b);
break;case 33:d=b.j;1<d.u&&(--d.u,C6(d).j=0);break;case 36:d=b.j;b=C6(d);for(a=0;15>=a;a++)for(c=0;32>=c;c++)if(d.B[a][c]===b){for(;32>=c;c++)d.B[a][c].reset();break}break;case 37:H6(b,2,d);break;case 38:H6(b,3,d);break;case 39:H6(b,4,d);break;case 40:D6(b.j,0,32);break;case 41:b.style.set(2);b.j=b.u;b.j.j=0;b.j.style=b.style;b.B.mode=1<<b.j.C;break;case 42:d=b.text;d.j=15;d.style.set(4);F6(d);PJa(b);break;case 43:PJa(b);break;case 44:a=b.u;switch(b.style.get()){case 1:case 2:case 3:B6(a,d)}E6(a,
0,15);break;case 45:b:{a=b.j;switch(b.style.get()){default:case 2:case 1:break b;case 4:if(15>a.row){++a.row;a.u=1;break b}case 3:}2>a.j&&(a.j=2,a.row<a.j&&(a.row=a.j));b=a.row-a.j+1;B6(a,d);NJa(a,b,b+1,a.j-1);E6(a,a.row,1)}break;case 46:E6(b.C,0,15);break;case 47:B6(b.u,d),b.C.updateTime(b.B.time+0),d=b.C,b.C=b.u,b.u=d,OJa(b)}break;case 7:switch(c){case 33:case 34:case 35:d=b.j,32<(d.u+=c&3)&&(d.u=32)}}},QJa=function(){},I6=function(a,b,c){this.trackData=a;
this.F=c;this.version=this.D=this.B=this.byteOffset=0;this.j=new DataView(this.trackData);this.u=[]},J6=function(a){var b=a.byteOffset;
a.byteOffset+=1;return a.j.getUint8(b)},K6=function(a){var b=a.byteOffset;
a.byteOffset+=4;return a.j.getUint32(b)},L6=function(a,b){n6.call(this);
this.B=a;this.C=b;this.track="CC3"===this.C.languageName?4:0;this.j=new x6;this.j.u=1<<this.track},M6=function(a){if("string"===typeof a)return!1;
a=new I6(a,8,0);return RJa(a)},RJa=function(a){if(!(a.byteOffset<a.j.byteLength)||1380139777!==K6(a))return!1;
a.version=J6(a);if(1<a.version)return!1;J6(a);J6(a);J6(a);return!0},N6=function(){n6.call(this)},SJa=function(a,b,c,d,e,f,h,l,m){switch(h.tagName){case "b":l.bold=!0;
break;case "i":l.italic=!0;break;case "u":l.underline=!0}for(var n=0;n<h.childNodes.length;n++){var p=h.childNodes[n];if(3===p.nodeType)p=new k6(b,c,d,e.id,p.nodeValue,f||0<n,g.zc(l)?void 0:l),m.push(p),e.j.push(p);else{var q={};Object.assign(q,l);SJa(a,b,c,d,e,!0,p,q,m)}}},O6=function(a){var b=a.split(":");
a=0;b=g.v(b);for(var c=b.next();!c.done;c=b.next())a=60*a+Number(c.value);return 1E3*a},TJa=function(a,b,c,d){d=Object.assign({Gr:0},d);
return new l6(a,b,c,"_"+m6++,d)},P6=function(a,b){g.F.call(this);
this.N=a;this.J=b;this.parser=null;this.j=this.N.Lq()},ZJa=function(a,b,c,d,e){d=d||0;
e=e||0;if(a.j&&b){var f=e,h=UJa(a,b,d),l=[];try{for(var m=g.v(h),n=m.next();!n.done;n=m.next()){var p=n.value,q=p.trackData,r=p.wF;l="string"!==typeof q?l.concat(VJa(a,c,q,r,f)):"WEBVTT"===q.substring(0,6)?l.concat(WJa(a,q,r)):l.concat(XJa(a,c,q,r))}var t=l}catch(u){g.R(u),a.clear(),t=[]}if(0!==t.length)return t}b=YJa(b);if(!b)return[];try{return"string"!==typeof b?VJa(a,c,b,d,e):"WEBVTT"===b.substring(0,6)?WJa(a,b,d):XJa(a,c,b,d)}catch(u){return g.R(u),a.clear(),[]}},YJa=function(a){if("string"===
typeof a||M6(a))return a;
var b=new DataView(a);if(8>=b.byteLength||1718909296!==b.getUint32(4))return"";b=g.oD(b,0,1835295092);if(!b||!b.size)return"";a=new Uint8Array(a,b.dataOffset,b.size-(b.dataOffset-b.offset));return g.Hz(a)},UJa=function(a,b,c){if("string"===typeof b||M6(b))return[{trackData:b,
wF:c}];var d=new DataView(b);if(8>=d.byteLength||1718909296!==d.getUint32(4))return[];var e=g.zD(d);if(a.j&&e){var f=g.lD(e),h=g.mD(e);e=e.j;f&&e&&a.j.Kw(e,f,h)}f=g.BD(d,1835295092);if(!f||!f.length||!f[0].size)return[];a=[];f=g.v(f.entries());for(h=f.next();!h.done;h=f.next())e=g.v(h.value),h=e.next().value,e=e.next().value,e=new Uint8Array(b,e.dataOffset,e.size-(e.dataOffset-e.offset)),e=g.Hz(e),a.push({trackData:e,wF:c+1E3*h});$Ja(d,a,c);return a=a.filter(function(l){return!!l.trackData})},$Ja=
function(a,b,c){var d=g.oD(a,0,1836476516),e=9E4;
d&&(e=g.qD(d)||9E4);d=0;var f=g.BD(a,1836019558);f=g.v(f.entries());for(var h=f.next();!h.done;h=f.next()){var l=g.v(h.value);h=l.next().value;l=l.next().value;h<b.length&&(l=g.oD(a,l.dataOffset,1953653094))&&(l=g.oD(a,l.dataOffset,1952867444))&&(l=g.wD(l)/e*1E3,0===h&&(d=l),b[h].wF=l-d+c||c*h*1E3)}},VJa=function(a,b,c,d,e){if(!M6(c))throw Error("Invalid binary caption track data");
a.parser||(a.parser=new L6(e,b));return a.parser.u(c,d)},WJa=function(a,b,c){a.parser||(a.parser=new N6);
a=a.parser.u(b,c);.01>Math.random()&&g.T(Error("Deprecated subtitles format in web player: WebVTT"));return a},XJa=function(a,b,c,d){if("{"===c[0])try{return a.parser||(a.parser=new u6(aKa(b))),a.parser.u(c,d)}catch(f){return g.R(f),[]}var e=iJa(c);
if(!e||!e.firstChild)throw a=Error("Invalid caption track data"),a.params=c,a;if("timedtext"===e.firstChild.tagName){if(3===Number(e.firstChild.getAttribute("format")))return a.parser||(a.parser=new o6(aKa(b),a.J)),a.parser.u(e,d);a=Error("Unsupported subtitles format in web player (Format2)");a.params=c;throw a;}if("transcript"===e.firstChild.tagName)throw a=Error("Unsupported subtitles format in web player (Format1)"),a.params=c,a;a=Error("Invalid caption track data");a.params=c;throw a;},aKa=function(a){var b=
{};
if(a=P5(a))b.lang=a,g.yua.test(a)&&(b.kf=1);return b},R6=function(a){g.PL.call(this,a);
var b=this;this.N=a;this.J=this.N.X();this.videoData=this.N.getVideoData();this.sb=this.N.Zb();this.B={Uc:{}};this.D={Uc:{}};this.Ba=[];this.V={};this.Ha={};this.ea=!1;this.vc=g.AK(this.videoData);this.fb=g.nka(this.videoData,this.N);this.Ib=!!this.videoData.captionTracks.length;this.Qb=!!this.videoData.Wj;this.Na="3"===this.J.controlsType;this.u=this.F=this.G=this.Fa=this.Xa=null;this.Wa=new P6(this.N,this.J);this.j=null;this.ya=new g.BF(this);this.K=new g.oL({S:"div",ra:"ytp-caption-window-container",
Ka:{id:"ytp-caption-window-container"}});this.T={top:0,right:0,bottom:0,left:0,width:1,height:1};var c=null,d=g.wm("yt-html5-player-modules::subtitlesModuleData");d&&(c=new g.bm(d));this.storage=c;var e;this.vb=!(null==(e=a.Vc())||!e.Hw());this.C=bKa(this);this.ma=!this.C&&this.Na&&this.vb&&this.fb;g.H(this,this.Wa);this.C?this.Ga=this.Aa=null:(this.Aa=new Q5(this.PF,void 0,this),g.H(this,this.Aa),this.Ga=new g.El(this.UR,2E3,this),g.H(this,this.Ga));g.H(this,this.ya);g.fL(this.player,this.K.element,
4);g.H(this,this.K);this.C||this.ya.oa(a,"resize",this.RF);(this.Cb=g.QH(this.J)&&!g.cw()&&!this.N.isFullscreen()&&!this.C&&!this.ma)&&this.ya.oa(a,"resize",this.GQ);this.ya.oa(a,"onPlaybackAudioChange",this.sQ);this.ya.oa(a,g.LK("captions"),function(f){b.onCueRangeEnter(f)});
this.ya.oa(a,"crx_captions",function(f){b.onCueRangeExit(f)});
Q6(this,S5()||{})},dKa=function(a){if(1===a.J.Aa||1===a.videoData.gt||"alwayson"===g.kK(a.videoData,"yt:cc"))return!0;
if(a.videoData.captionTracks.length)var b=a.player.getAudioTrack().B;if(2===a.J.Aa){if(g.hI(a.J))var c=cKa(a);else if(a.storage)try{c=a.storage.get("module-enabled")}catch(e){a.storage.remove("module-enabled")}else c=null;if(null!=c)return!!c}c=N5(a.player.getAudioTrack(),g.hI(a.J));var d=g.kK(a.videoData,"yt:cc");if(void 0===S6(a)){if("CAPTIONS_INITIAL_STATE_ON_RECOMMENDED"===c)return d?"on"===d:!0;if("CAPTIONS_INITIAL_STATE_OFF_RECOMMENDED"===c)return"on"===d}else return"on"===d;return"ON"===b||
"on"===g.kK(a.videoData,"yt:cc")},T6=function(a,b){if(a.j&&(void 0===b||!b)||!a.videoData.captionTracks.length)return!1;
a=a.player.getAudioTrack();return!!a.u||"FORCED_ON"===a.B},S6=function(a){var b=void 0,c=g.Sq(g.Qq.getInstance(),65);
if(g.hI(a.J)&&null!=c){if(null!=cKa(a))return!1;b=!c}return b},eKa=function(a){if(a.vc)a=new h6(a.J,a.videoData,a.player.getAudioTrack(),a.player);
else if(a.fb)a=new Z5(a.videoData.j,a.player);else if(a.Ib)a=new W5(a.J,a.videoData,a.player.getAudioTrack());else{var b=a.videoData;a=new $5(a.J,a.videoData.Wj,a.videoData.videoId,b.captionsLanguagePreference||b.u.captionsLanguagePreference||g.kK(b,"yt:cc_default_lang")||b.u.zc,a.videoData.Kt)}return a},V6=function(a,b){if(a.u){if(a.F&&a.F.C)return a.F.C;
b||(b=a.Qb?!1:a.Ib?!1:!0);b=b||!!g.Sq(g.Qq.getInstance(),66);b=T5(a.u.u,b);if(OIa(a.J)){var c=a.N.isInline()?void 0:g.rx("yt-player-caption-sticky-language");c=[c,a.videoData.captionsLanguagePreference,a.J.captionsLanguagePreference,g.kK(a.videoData,"yt:cc_default_lang")];for(var d=!1,e=0;e<c.length;e++){var f=c[e];if(f){d=!0;for(var h=0;h<b.length;h++)if(P5(b[h])===f)return b[h];f=f.split("-")[0];for(h=0;h<b.length;h++)if(P5(b[h])===f)return b[h]}}if(d){var l;return(null==(l=a.F)?void 0:l.j)||U6(a)}}else for(l=
[a.videoData.captionsLanguagePreference,a.J.captionsLanguagePreference,g.kK(a.videoData,"yt:cc_default_lang")],c=0;c<l.length;c++)for(d=0;d<b.length;d++)if(P5(b[d])===l[c])return b[d];return a.F&&a.F.j?a.F.j:(l=b.find(function(m){return m.isDefault}))?l:b[0]||U6(a)}return null},U6=function(a){return a.F&&a.F.u},W6=function(a){var b=U6(a);
return!!b&&a.j===b},fKa=function(a){T5(a.u.u,!0);
var b=N5(a.player.getAudioTrack(),g.hI(a.J)),c;"CAPTIONS_INITIAL_STATE_ON_REQUIRED"===b?c=V6(a,a.ea):"CAPTIONS_INITIAL_STATE_OFF_REQUIRED"===b&&T6(a)?c=U6(a):S6(a)||a.ea||dKa(a)?c=V6(a,a.ea):T6(a)&&(c=U6(a));if(a.C||a.ma){var d=T5(a.u.u,!0);b=[];for(var e=0;e<d.length;e++){var f=d[e],h=g.ee("TRACK");h.setAttribute("kind","subtitles");h.setAttribute("label",g.BI(f));h.setAttribute("srclang",P5(f));h.setAttribute("id",f.toString());a.ma||h.setAttribute("src",a.u.Oq(f,"vtt"));f===c&&h.setAttribute("default",
"1");b.push(h)}c=a.N.Vc();c.Qt(b);c=c.Zc();a.vb&&a.ya.oa(c.textTracks,"change",a.rR)}else!a.j&&c&&X6(a,c),a.player.Ia("onCaptionsTrackListChanged"),a.player.Ia("onApiChange")},gKa=function(a,b){var c=a.N.Vc().Zc().textTracks;
a=a.j.toString();for(var d=0;d<c.length;d++){var e=c[d];e.id===a&&(b?"showing"!==e.mode&&(e.mode="showing"):"showing"===e.mode&&(e.mode="disabled"))}},X6=function(a,b,c){a.loaded&&a.unload();
null!=c&&(a.ea=c,a.ea&&(g.hI(a.J)?c$(a,!!b):d$(a,!!b)));a.j=b;T6(a)&&(a.j=U6(a));a.load()},iKa=function(a,b){if(b instanceof l6){var c=a.V[b.id];
c&&c.u!==b&&(c.dispose(),delete a.V[b.id],c=null);c||(c=hKa(a,b))&&(a.V[b.id]=c)}else c=b.windowId,a.Ha[c]||(a.Ha[c]=[]),a.Ha[c].push(b)},hKa=function(a,b){var c=a.sb.getVideoContentRect(!0).height,d=a.sb.getVideoContentRect(!0).width;
if(!c||!d)return null;var e=a.j?P5(a.j):null;e&&g.yua.test(e)&&(b.params.kf=1);var f=a.sb.getPlayerSize();c*=a.T.height;d*=a.T.width;e=f.height*a.T.height;f=f.width*a.T.width;"google-live"!==a.J.playerStyle||a.B.isDefault||Object.assign(b.params,a.B);switch(null!=b.params.Gr?b.params.Gr:1<b.j.length?1:0){case 1:return new i6(b,a.B,a.D,d,c,f,e,a.J.experiments,a.RA.bind(a),a.N);case 2:return new j6(b,a.B,a.D,d,c,f,e,a.J.experiments,a.RA.bind(a),a.N);default:return new g6(b,a.B,a.D,d,c,f,e,a.J.experiments,
a.RA.bind(a),a.N)}},Q6=function(a,b,c){c=void 0===c?!1:c;
var d=h$.Uc;a.B={};Object.assign(a.B,h$);a.B.Uc={};Object.assign(a.B.Uc,d);a.D={Uc:{}};var e=b.backgroundOverride?a.D:a.B,f=b.background||d.background;s6.test(f);e.Uc.background=f;e=b.colorOverride?a.D:a.B;f=b.color||d.color;s6.test(f);e.Uc.color=f;e=b.windowColorOverride?a.D:a.B;f=b.windowColor||h$.windowColor;s6.test(f);e.windowColor=f;e=b.backgroundOpacityOverride?a.D:a.B;f=b.backgroundOpacity;null==f&&(f=d.backgroundOpacity);e.Uc.backgroundOpacity=f;e=b.fontSizeIncrementOverride?a.D:a.B;f=b.fontSizeIncrement;
null==f&&(f=d.fontSizeIncrement);e.Uc.fontSizeIncrement=f;f=b.fontStyleOverride?a.D:a.B;e=b.fontStyle;null==e&&(e=d.bold&&d.italic?3:d.bold?1:d.italic?2:0);f=f.Uc;switch(e){case 1:f.bold=!0;delete f.italic;break;case 2:delete f.bold;f.italic=!0;break;case 3:f.bold=!0;f.italic=!0;break;default:delete f.bold,delete f.italic}e=b.textOpacityOverride?a.D:a.B;f=b.textOpacity;null==f&&(f=d.textOpacity);e.Uc.textOpacity=f;e=b.windowOpacityOverride?a.D:a.B;f=b.windowOpacity;null==f&&(f=h$.windowOpacity);e.windowOpacity=
f;e=b.charEdgeStyleOverride?a.D:a.B;f=b.charEdgeStyle;null==f&&(f=d.charEdgeStyle);e.Uc.charEdgeStyle=f;e=b.fontFamilyOverride?a.D:a.B;f=b.fontFamily;null==f&&(f=d.fontFamily);e.Uc.fontFamily=f;a.loaded&&a.RF();c&&g.qx("yt-player-caption-display-settings",b,2592E3)},j$=function(a,b,c){b&&!a.G?(b=vJa({kf:0,
lang:"en"}),a.G=[b,new k6(b.start,b.end-b.start,0,b.id,null!=c?c:"Captions look like this")],a.player.Rg(a.G)):!b&&a.G&&(jKa(a,a.G),a.G=null)},jKa=function(a,b){a.player.jf(b);
b=g.v(b);for(var c=b.next();!c.done;c=b.next())g.pb(a.Ba,c.value);R5(a.Aa)},d$=function(a,b){if(a.storage)try{a.storage.set("module-enabled",b)}catch(c){}},c$=function(a,b){a.N.isInline()||g.qx("yt-player-sticky-caption",b,2592E3)},cKa=function(a){if(!a.N.isInline())return g.rx("yt-player-sticky-caption")},bKa=function(a){var b,c=!(null==(b=a.N.Vc())||!b.Gw());
return a.Na&&c&&!a.fb};
g.iN.prototype.Ju=g.ea(58,function(a){var b=2;this.Na.has(a)?b=0:g.Yla(this,a)&&(b=1);return b});
g.ER.prototype.Ju=g.ea(57,function(a){return this.yc.Ju(a)});
g.iN.prototype.Kw=g.ea(56,function(a,b,c){this.Ba.set(a,{yq:b,Nt:c})});
g.ER.prototype.Kw=g.ea(55,function(a,b,c){this.yc.Kw(a,b,c)});
g.kM.prototype.lq=g.ea(54,function(){var a=g.Vd(document,"track",void 0,this.j);for(var b=0;b<a.length;b++)g.je(a[b])});
g.SM.prototype.lq=g.ea(53,function(){this.mediaElement.lq()});
g.kM.prototype.Hw=g.ea(52,function(){return!(!this.j.textTracks||!this.j.textTracks.addEventListener)});
g.SM.prototype.Hw=g.ea(51,function(){return this.mediaElement.Hw()});
g.kM.prototype.Gw=g.ea(50,function(){return!!this.j.textTracks});
g.SM.prototype.Gw=g.ea(49,function(){return this.mediaElement.Gw()});
g.kM.prototype.Qt=g.ea(48,function(a){for(var b=0;b<a.length;b++)this.j.appendChild(a[b])});
g.SM.prototype.Qt=g.ea(47,function(a){this.mediaElement.Qt(a)});
g.sR.prototype.Uu=g.ea(12,function(){return this.G});
g.HT.prototype.Uu=g.ea(11,function(){var a;return(null==(a=g.TK(this))?void 0:a.Lq())||null});
g.bL.prototype.Lq=g.ea(10,function(){return this.app.Uu()});
g.fT.prototype.Lq=g.ea(9,function(){var a;return(null==(a=this.qa)?void 0:a.Uu())||null});
g.AC.prototype.qy=g.ea(8,function(a){return(a=this.vj(a))?a.j:0});
g.eF.prototype.qy=g.ea(7,function(){return 0});
g.Va(Q5,g.F);g.k=Q5.prototype;g.k.start=function(){this.stop();this.C=!1;var a=TIa(this),b=UIa(this);a&&!b&&this.u.mozRequestAnimationFrame?(this.j=g.Mc(this.u,"MozBeforePaint",this.B),this.u.mozRequestAnimationFrame(null),this.C=!0):this.j=a&&b?a.call(this.u,this.B):this.u.setTimeout(SIa(this.B),20)};
g.k.stop=function(){if(this.isActive()){var a=TIa(this),b=UIa(this);a&&!b&&this.u.mozRequestAnimationFrame?g.Uc(this.j):a&&b?b.call(this.u,this.j):this.u.clearTimeout(this.j)}this.j=null};
g.k.isActive=function(){return null!=this.j};
g.k.SM=function(){this.C&&this.j&&g.Uc(this.j);this.j=null;this.F.call(this.D,g.Ua())};
g.k.va=function(){this.stop();Q5.Gf.va.call(this)};
var $Ia={aa:"Afar",ab:"Abkhazian",ace:"Achinese",ach:"Acoli",ada:"Adangme",ady:"Adyghe",ae:"Avestan",aeb:"Tunisian Arabic",af:"Afrikaans",afh:"Afrihili",agq:"Aghem",ain:"Ainu",ak:"Akan",akk:"Akkadian",akz:"Alabama",ale:"Aleut",aln:"Gheg Albanian",alt:"Southern Altai",am:"Amharic",an:"Aragonese",ang:"Old English",anp:"Angika",ar:"Arabic",ar_001:"Arabic (world)",arc:"Aramaic",arn:"Mapuche",aro:"Araona",arp:"Arapaho",arq:"Algerian Arabic",ars:"Najdi Arabic",arw:"Arawak",ary:"Moroccan Arabic",arz:"Egyptian Arabic",
as:"Assamese",asa:"Asu",ase:"American Sign Language",ast:"Asturian",av:"Avaric",avk:"Kotava",awa:"Awadhi",ay:"Aymara",az:"Azerbaijani",az_Cyrl:"Azerbaijani (Cyrillic)",az_Latn:"Azerbaijani (Latin)",ba:"Bashkir",bal:"Baluchi",ban:"Balinese",bar:"Bavarian",bas:"Basaa",bax:"Bamun",bbc:"Batak Toba",bbj:"Ghomala",be:"Belarusian",bej:"Beja",bem:"Bemba",bew:"Betawi",bez:"Bena",bfd:"Bafut",bfq:"Badaga",bg:"Bulgarian",bgc:"Haryanvi",bgn:"Western Balochi",bho:"Bhojpuri",bi:"Bislama",bik:"Bikol",bin:"Bini",
bjn:"Banjar",bkm:"Kom",bla:"Siksik\u00e1",bm:"Bambara",bn:"Bangla",bo:"Tibetan",bpy:"Bishnupriya",bqi:"Bakhtiari",br:"Breton",bra:"Braj",brh:"Brahui",brx:"Bodo",bs:"Bosnian",bs_Cyrl:"Bosnian (Cyrillic)",bs_Latn:"Bosnian (Latin)",bss:"Akoose",bua:"Buriat",bug:"Buginese",bum:"Bulu",byn:"Blin",byv:"Medumba",ca:"Catalan",cad:"Caddo",car:"Carib",cay:"Cayuga",cch:"Atsam",ccp:"Chakma",ce:"Chechen",ceb:"Cebuano",cgg:"Chiga",ch:"Chamorro",chb:"Chibcha",chg:"Chagatai",chk:"Chuukese",chm:"Mari",chn:"Chinook Jargon",
cho:"Choctaw",chp:"Chipewyan",chr:"Cherokee",chy:"Cheyenne",ckb:"Central Kurdish",ckb_Arab:"Central Kurdish (Arabic)",co:"Corsican",cop:"Coptic",cps:"Capiznon",cr:"Cree",crh:"Crimean Tatar",cs:"Czech",csb:"Kashubian",cu:"Church Slavic",cv:"Chuvash",cy:"Welsh",da:"Danish",dak:"Dakota",dar:"Dargwa",dav:"Taita",de:"German",de_AT:"German (Austria)",de_CH:"German (Switzerland)",del:"Delaware",den:"Slave",dgr:"Dogrib",din:"Dinka",dje:"Zarma",doi:"Dogri",dsb:"Lower Sorbian",dua:"Duala",dum:"Middle Dutch",
dv:"Divehi",dyo:"Jola-Fonyi",dyu:"Dyula",dz:"Dzongkha",dzg:"Dazaga",ebu:"Embu",ee:"Ewe",efi:"Efik",egy:"Ancient Egyptian",eka:"Ekajuk",el:"Greek",elx:"Elamite",en:"English",en_AU:"English (Australia)",en_CA:"English (Canada)",en_GB:"English (United Kingdom)",en_US:"English (United States)",enm:"Middle English",eo:"Esperanto",es:"Spanish",es_419:"Spanish (Latin America)",es_ES:"Spanish (Spain)",es_MX:"Spanish (Mexico)",et:"Estonian",eu:"Basque",ewo:"Ewondo",fa:"Persian",fa_AF:"Persian (Afghanistan)",
fan:"Fang",fat:"Fanti",ff:"Fula",ff_Adlm:"Fula (Adlam)",ff_Latn:"Fula (Latin)",fi:"Finnish",fil:"Filipino",fj:"Fijian",fo:"Faroese",fon:"Fon",fr:"French",fr_CA:"French (Canada)",fr_CH:"French (Switzerland)",frm:"Middle French",fro:"Old French",frr:"Northern Frisian",frs:"Eastern Frisian",fur:"Friulian",fy:"Western Frisian",ga:"Irish",gaa:"Ga",gay:"Gayo",gba:"Gbaya",gd:"Scottish Gaelic",gez:"Geez",gil:"Gilbertese",gl:"Galician",gmh:"Middle High German",gn:"Guarani",goh:"Old High German",gon:"Gondi",
gor:"Gorontalo",got:"Gothic",grb:"Grebo",grc:"Ancient Greek",gsw:"Swiss German",gu:"Gujarati",guz:"Gusii",gv:"Manx",gwi:"Gwich\u02bcin",ha:"Hausa",hai:"Haida",haw:"Hawaiian",he:"Hebrew",hi:"Hindi",hi_Latn:"Hindi (Latin)",hil:"Hiligaynon",hit:"Hittite",hmn:"Hmong",ho:"Hiri Motu",hr:"Croatian",hsb:"Upper Sorbian",ht:"Haitian Creole",hu:"Hungarian",hup:"Hupa",hy:"Armenian",hz:"Herero",ia:"Interlingua",iba:"Iban",ibb:"Ibibio",id:"Indonesian",ie:"Interlingue",ig:"Igbo",ii:"Sichuan Yi",ik:"Inupiaq",ilo:"Iloko",
"in":"Indonesian",inh:"Ingush",io:"Ido",is:"Icelandic",it:"Italian",iu:"Inuktitut",iw:"Hebrew",ja:"Japanese",jbo:"Lojban",jgo:"Ngomba",jmc:"Machame",jpr:"Judeo-Persian",jrb:"Judeo-Arabic",jv:"Javanese",ka:"Georgian",kaa:"Kara-Kalpak",kab:"Kabyle",kac:"Kachin",kaj:"Jju",kam:"Kamba",kaw:"Kawi",kbd:"Kabardian",kbl:"Kanembu",kcg:"Tyap",kde:"Makonde",kea:"Kabuverdianu",kfo:"Koro",kg:"Kongo",kgp:"Kaingang",kha:"Khasi",kho:"Khotanese",khq:"Koyra Chiini",ki:"Kikuyu",kj:"Kuanyama",kk:"Kazakh",kkj:"Kako",kl:"Kalaallisut",
kln:"Kalenjin",km:"Khmer",kmb:"Kimbundu",kn:"Kannada",ko:"Korean",kok:"Konkani",kos:"Kosraean",kpe:"Kpelle",kr:"Kanuri",krc:"Karachay-Balkar",krl:"Karelian",kru:"Kurukh",ks:"Kashmiri",ks_Arab:"Kashmiri (Arabic)",ks_Deva:"Kashmiri (Devanagari)",ksb:"Shambala",ksf:"Bafia",ksh:"Colognian",ku:"Kurdish",kum:"Kumyk",kut:"Kutenai",kv:"Komi",kw:"Cornish",ky:"Kyrgyz",la:"Latin",lad:"Ladino",lag:"Langi",lah:"Western Panjabi",lam:"Lamba",lb:"Luxembourgish",lez:"Lezghian",lg:"Ganda",li:"Limburgish",lkt:"Lakota",
ln:"Lingala",lo:"Lao",lol:"Mongo",loz:"Lozi",lrc:"Northern Luri",lt:"Lithuanian",lu:"Luba-Katanga",lua:"Luba-Lulua",lui:"Luiseno",lun:"Lunda",luo:"Luo",lus:"Mizo",luy:"Luyia",lv:"Latvian",mad:"Madurese",maf:"Mafa",mag:"Magahi",mai:"Maithili",mak:"Makasar",man:"Mandingo",mas:"Masai",mde:"Maba",mdf:"Moksha",mdr:"Mandar",men:"Mende",mer:"Meru",mfe:"Morisyen",mg:"Malagasy",mga:"Middle Irish",mgh:"Makhuwa-Meetto",mgo:"Meta\u02bc",mh:"Marshallese",mi:"M\u0101ori",mic:"Mi'kmaq",min:"Minangkabau",mk:"Macedonian",
ml:"Malayalam",mn:"Mongolian",mnc:"Manchu",mni:"Manipuri",mni_Beng:"Manipuri (Bangla)",mo:"Romanian",moh:"Mohawk",mos:"Mossi",mr:"Marathi",ms:"Malay",mt:"Maltese",mua:"Mundang",mul:"Multiple languages",mus:"Muscogee",mwl:"Mirandese",mwr:"Marwari",my:"Burmese",mye:"Myene",myv:"Erzya",mzn:"Mazanderani",na:"Nauru",nap:"Neapolitan",naq:"Nama",nb:"Norwegian Bokm\u00e5l",nd:"North Ndebele",nds:"Low German",nds_NL:"Low German (Netherlands)",ne:"Nepali","new":"Newari",ng:"Ndonga",nia:"Nias",niu:"Niuean",
nl:"Dutch",nl_BE:"Dutch (Belgium)",nmg:"Kwasio",nn:"Norwegian Nynorsk",nnh:"Ngiemboon",no:"Norwegian",nog:"Nogai",non:"Old Norse",nqo:"N\u2019Ko",nr:"South Ndebele",nso:"Northern Sotho",nus:"Nuer",nv:"Navajo",nwc:"Classical Newari",ny:"Nyanja",nym:"Nyamwezi",nyn:"Nyankole",nyo:"Nyoro",nzi:"Nzima",oc:"Occitan",oj:"Ojibwa",om:"Oromo",or:"Odia",os:"Ossetic",osa:"Osage",ota:"Ottoman Turkish",pa:"Punjabi",pa_Arab:"Punjabi (Arabic)",pa_Guru:"Punjabi (Gurmukhi)",pag:"Pangasinan",pal:"Pahlavi",pam:"Pampanga",
pap:"Papiamento",pau:"Palauan",pcm:"Nigerian Pidgin",peo:"Old Persian",phn:"Phoenician",pi:"Pali",pl:"Polish",pon:"Pohnpeian",pro:"Old Proven\u00e7al",ps:"Pashto",pt:"Portuguese",pt_BR:"Portuguese (Brazil)",pt_PT:"Portuguese (Portugal)",qu:"Quechua",raj:"Rajasthani",rap:"Rapanui",rar:"Rarotongan",rm:"Romansh",rn:"Rundi",ro:"Romanian",ro_MD:"Romanian (Moldova)",rof:"Rombo",rom:"Romany",ru:"Russian",rup:"Aromanian",rw:"Kinyarwanda",rwk:"Rwa",sa:"Sanskrit",sad:"Sandawe",sah:"Yakut",sam:"Samaritan Aramaic",
saq:"Samburu",sas:"Sasak",sat:"Santali",sat_Olck:"Santali (Ol Chiki)",sba:"Ngambay",sbp:"Sangu",sc:"Sardinian",scn:"Sicilian",sco:"Scots",sd:"Sindhi",sd_Arab:"Sindhi (Arabic)",sd_Deva:"Sindhi (Devanagari)",se:"Northern Sami",see:"Seneca",seh:"Sena",sel:"Selkup",ses:"Koyraboro Senni",sg:"Sango",sga:"Old Irish",sh:"Serbo-Croatian",shi:"Tachelhit",shi_Latn:"Tachelhit (Latin)",shi_Tfng:"Tachelhit (Tifinagh)",shn:"Shan",shu:"Chadian Arabic",si:"Sinhala",sid:"Sidamo",sk:"Slovak",sl:"Slovenian",sm:"Samoan",
sma:"Southern Sami",smj:"Lule Sami",smn:"Inari Sami",sms:"Skolt Sami",sn:"Shona",snk:"Soninke",so:"Somali",sog:"Sogdien",sq:"Albanian",sr:"Serbian",sr_Cyrl:"Serbian (Cyrillic)",sr_Latn:"Serbian (Latin)",srn:"Sranan Tongo",srr:"Serer",ss:"Swati",ssy:"Saho",st:"Southern Sotho",su:"Sundanese",su_Latn:"Sundanese (Latin)",suk:"Sukuma",sus:"Susu",sux:"Sumerian",sv:"Swedish",sw:"Swahili",sw_CD:"Swahili (Congo - Kinshasa)",swb:"Comorian",syc:"Classical Syriac",syr:"Syriac",ta:"Tamil",te:"Telugu",tem:"Timne",
teo:"Teso",ter:"Tereno",tet:"Tetum",tg:"Tajik",th:"Thai",ti:"Tigrinya",tig:"Tigre",tiv:"Tiv",tk:"Turkmen",tkl:"Tokelau",tl:"Tagalog",tlh:"Klingon",tli:"Tlingit",tmh:"Tamashek",tn:"Tswana",to:"Tongan",tog:"Nyasa Tonga",tpi:"Tok Pisin",tr:"Turkish",trv:"Taroko",ts:"Tsonga",tsi:"Tsimshian",tt:"Tatar",tum:"Tumbuka",tvl:"Tuvalu",tw:"Twi",twq:"Tasawaq",ty:"Tahitian",tyv:"Tuvinian",tzm:"Central Atlas Tamazight",udm:"Udmurt",ug:"Uyghur",uga:"Ugaritic",uk:"Ukrainian",umb:"Umbundu",ur:"Urdu",uz:"Uzbek",uz_Arab:"Uzbek (Arabic)",
uz_Cyrl:"Uzbek (Cyrillic)",uz_Latn:"Uzbek (Latin)",vai:"Vai",vai_Latn:"Vai (Latin)",vai_Vaii:"Vai (Vai)",ve:"Venda",vi:"Vietnamese",vo:"Volap\u00fck",vot:"Votic",vun:"Vunjo",wa:"Walloon",wae:"Walser",wal:"Wolaytta",war:"Waray",was:"Washo",wo:"Wolof",xal:"Kalmyk",xh:"Xhosa",xog:"Soga",yao:"Yao",yap:"Yapese",yav:"Yangben",ybb:"Yemba",yi:"Yiddish",yo:"Yoruba",yrl:"Nheengatu",yue:"Cantonese",yue_Hans:"Cantonese (Simplified)",yue_Hant:"Cantonese (Traditional)",za:"Zhuang",zap:"Zapotec",zbl:"Blissymbols",
zen:"Zenaga",zgh:"Standard Moroccan Tamazight",zh:"Chinese",zh_Hans:"Chinese (Simplified)",zh_Hant:"Chinese (Traditional)",zh_TW:"Chinese (Taiwan)",zu:"Zulu",zun:"Zuni",zxx:"No linguistic content",zza:"Zaza"};g.y(V5,g.F);g.k=V5.prototype;g.k.Fv=function(){};
g.k.Gv=function(){};
g.k.Dl=function(){};
g.k.Oq=function(){return""};
g.k.XK=function(){return!1};
g.k.va=function(){this.Dl();g.F.prototype.va.call(this)};
g.y(W5,V5);W5.prototype.Fv=function(a,b,c){var d=this;this.isDisposed();b=this.Oq(a,b);this.Dl();this.j=g.Lp(b,{format:"RAW",onSuccess:function(e){d.j=null;c(e.responseText,a)},
withCredentials:!0})};
W5.prototype.Gv=function(a){if(this.audioTrack)for(var b=g.v(this.audioTrack.captionTracks),c=b.next();!c.done;c=b.next())U5(this.u,c.value);a()};
W5.prototype.Oq=function(a,b){var c=a.Wd(),d={fmt:b};if("srv3"===b||"3"===b||"json3"===b)g.eq()?Object.assign(d,{xorb:2,xobt:1,xovt:1}):Object.assign(d,{xorb:2,xobt:3,xovt:3});a.translationLanguage&&(d.tlang=P5(a));this.J.I("web_player_topify_subtitles_for_shorts")&&this.B&&(d.xosf="1");Object.assign(d,this.J.deviceParams);return g.ap(c,d)};
W5.prototype.Dl=function(){this.j&&this.j.abort()};
X5.prototype.contains=function(a){a=g.xb(this.segments,a);return 0<=a||0>a&&1===(-a-1)%2};
X5.prototype.length=function(){return this.segments.length/2};
g.y(Y5,g.F);g.k=Y5.prototype;g.k.va=function(){g.F.prototype.va.call(this);this.B&&this.B.cancel()};
g.k.pz=function(){this.seekTo(this.player.getCurrentTime())};
g.k.seekTo=function(a){a-=this.player.Hc();var b=this.j;this.j=g.fb(this.V.zm(a).Ja);b!==this.j&&this.T&&this.T()};
g.k.reset=function(){this.C=new X5;this.F=-1;this.B&&(this.B.cancel(),this.B=null)};
g.k.PJ=function(){this.isDisposed();var a;if(a=null!=this.j)a=this.j,a=a.j.Gl(a);if(a&&!this.B&&!(this.j&&30<this.j.startTime-this.player.getCurrentTime())){a=this.j;a=a.j.kt(a);var b;if(null==(b=this.player.getVideoData())?0:b.enableServerStitchedDai)if(b=this.player.Lq()){var c=a.Ja[0].j.info.id,d=a.Ja[0].xa,e=a.Ja[0].B;if(this.policy.Na){if(b=b.Ko(e,d,c,3))a.G=b}else if(c=b.wj(e,d,c,3))if(b=b.Ju(d),0===b)c&&(a.u=new g.oC(c));else if(2===b){this.G.start();YIa(this)&&this.seekTo(this.player.getCurrentTime());
return}}a.Ja[0].duration?(this.C.contains(a.Ja[0].xa)||ZIa(this,a),this.j=g.fb(a.Ja)):YIa(this)&&this.seekTo(this.player.getCurrentTime())}this.G.start()};
g.y(Z5,V5);g.k=Z5.prototype;g.k.Fv=function(a,b,c){var d=this;this.Dl();b=bJa(this,a.getId());b||(b=a.languageCode,b=this.j.isManifestless?cJa(this,b,"386"):cJa(this,b));if(b){var e=1E3*(b.index.qy(b.index.Zh())-b.index.getStartTime(b.index.Zh())),f=new g.QL(this.J);this.B=new Y5(f,this.N,b,function(h,l){c(h,a,l,e)},this.F||g.VE(b.info),function(){d.B&&d.B.reset();
d.D=!0})}};
g.k.XK=function(){var a=this.D;this.D=!1;return a};
g.k.Gv=function(a){var b=this.F?[new g.AI({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.AI({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]:this.j.isManifestless?aJa(this,"386"):aJa(this);b=g.v(b);for(var c=b.next();!c.done;c=b.next())U5(this.u,c.value);a()};
g.k.Dl=function(){this.B&&(this.B.dispose(),this.B=null)};
g.k.Oq=function(){return""};
g.y($5,V5);$5.prototype.Fv=function(a,b,c){var d=this;this.isDisposed();b=this.Oq(a,b);this.Dl();this.j=g.Lp(b,{format:"RAW",onSuccess:function(e){d.j=null;c(e.responseText,a)},
withCredentials:!0})};
$5.prototype.Gv=function(a){var b=this,c=this.B,d={type:"list",tlangs:1,v:this.videoId,vssids:1};this.D&&(d.asrs=1);c=g.ap(c,d);this.Dl();this.j=g.Lp(c,{format:"RAW",onSuccess:function(e){b.j=null;if((e=e.responseXML)&&e.firstChild){for(var f=e.getElementsByTagName("track"),h=0;h<f.length;h++){var l=f[h],m=l.getAttribute("lang_code"),n=l.getAttribute("lang_translated"),p=l.getAttribute("name"),q=l.getAttribute("kind"),r=l.getAttribute("id"),t="true"===l.getAttribute("lang_default"),u="true"===l.getAttribute("cantran");
l=l.getAttribute("vss_id");U5(b.u,new g.AI({languageCode:m,languageName:n,name:p,kind:q,id:r,is_servable:!0,is_translateable:u,vss_id:l,is_default:t}))}e=e.getElementsByTagName("target");f=e.length;for(h=0;h<f;h++)m={languageCode:e[h].getAttribute("lang_code"),languageName:e[h].getAttribute("lang_translated"),languageOriginal:e[h].getAttribute("lang_original"),id:e[h].getAttribute("id"),isDefault:"true"===e[h].getAttribute("lang_default")},b.F[m.languageCode]=m.languageName,b.C.push(m)}a()},
withCredentials:!0})};
$5.prototype.Oq=function(a,b){var c=this.B;b={v:this.videoId,type:"track",lang:a.languageCode,name:a.getName(),kind:a.kind,fmt:b};a.translationLanguage&&(b.tlang=P5(a));Object.assign(b,this.J.deviceParams);return c=g.ap(c,b)};
$5.prototype.Dl=function(){this.j&&this.j.abort()};
var s6=/^#(?:[0-9a-f]{3}){1,2}$/i;g.y(b6,g.Bx);g.k=b6.prototype;g.k.oa=function(a,b){this.C.oa(this.K,a,b,void 0,!this.j)};
g.k.cancel=function(){this.B&&(this.B=!1,this.Z("dragend",0,0,null));this.u&&(this.u=!1,this.Z("hoverend",0,0,null),c6(this),a6(this))};
g.k.bp=function(a){c6(this);this.oa(d6("move"),this.BG);this.oa(d6("out"),this.Hr);this.oa("touchstart",this.MA);this.j&&this.oa(d6("down"),this.LA);var b=g.cu(a);a=g.fu(a);this.u=!0;this.Z("hoverstart",a.x,a.y,b);this.Z("hovermove",a.x,a.y,b)};
g.k.BG=function(a){var b=g.cu(a);a=g.fu(a);if(this.D){var c=this.D;this.D=null;if(g.eu(c)===b&&g.Hd(g.fu(c),a))return}this.Z("hovermove",a.x,a.y,b)};
g.k.Hr=function(a){var b=g.fu(a),c=g.eu(a);try{if(c&&g.le(this.target,c)){this.D=a;this.Z("hovermove",b.x,b.y,c);return}}catch(d){}c6(this);a6(this);this.u=!1;this.Z("hoverend",b.x,b.y,c)};
g.k.LP=function(a){this.bp(a);this.LA(a)};
g.k.LA=function(a){if("number"!==typeof a.button||0===a.button){c6(this);this.C.oa(document,d6("move"),this.KP);this.C.oa(document,d6("up"),this.ZM);var b=g.cu(a);if(g.kl)this.oa("dragstart",this.pO);else if(g.gu(a),(g.RO||g.ll)&&b)a:{for(var c=b;c;){if(g.qe(c)||"-1"===c.getAttribute("tabindex")){c.focus();break a}c=c.parentElement}document.activeElement.blur()}this.B=!0;a=g.fu(a);this.Z("dragstart",a.x,a.y,b);this.Z("dragmove",a.x,a.y,b)}};
g.k.pO=function(a){g.gu(a)};
g.k.KP=function(a){var b=g.cu(a);b===document&&(b=null);a=g.fu(a);this.Z("hovermove",a.x,a.y,b);this.Z("dragmove",a.x,a.y,b)};
g.k.ZM=function(a){c6(this);this.B=!1;var b=g.du(a),c=g.cu(a);a=g.fu(a);b&&g.le(this.target,b)?(this.oa(d6("move"),this.BG),this.oa(d6("out"),this.Hr),this.oa(d6("down"),this.LA),this.oa("touchstart",this.MA),this.Z("dragend",a.x,a.y,c)):(a6(this),this.u=!1,this.Z("dragend",a.x,a.y,c),this.Z("hoverend",a.x,a.y,c))};
g.k.MA=function(a){var b=a.changedTouches[0];b&&(c6(this),this.oa("touchmove",this.HS),this.oa("touchend",this.CG),this.oa("touchcancel",this.CG),this.F=b.identifier,a=g.cu(a),this.u||(this.u=!0,this.Z("hoverstart",b.pageX,b.pageY,a)),this.Z("hovermove",b.pageX,b.pageY,a),this.j&&(this.B=!0,this.Z("dragstart",b.pageX,b.pageY,a),this.Z("dragmove",b.pageX,b.pageY,a)))};
g.k.HS=function(a){var b=dJa(this,a);b&&(this.j&&g.gu(a),a=g.cu(a),this.Z("hovermove",b.pageX,b.pageY,a),this.j&&this.Z("dragmove",b.pageX,b.pageY,a))};
g.k.CG=function(a){var b=dJa(this,a);if(b){c6(this);a6(this);this.u=!1;var c=g.cu(a);this.j&&(this.G||g.gu(a),this.B=!1,this.Z("dragend",b.pageX,b.pageY,c));this.Z("hoverend",b.pageX,b.pageY,c)}};
g.k.va=function(){this.j&&(g.kl&&this.target.removeAttribute("draggable"),this.target.style.touchAction="");c6(this);g.Bx.prototype.va.call(this)};
var fJa=/#(.)(.)(.)/,eJa=/^#(?:[0-9a-f]{3}){1,2}$/i;var hJa=g.pe&&gJa();var f6=window.yt&&window.yt.msgs_||window.ytcfg&&window.ytcfg.msgs||{};g.Ga("yt.msgs_",f6);var mJa=["left","right","center","justify"];g.y(g6,g.oL);g.k=g6.prototype;g.k.AQ=function(a,b){this.vb=a;this.Cb=b;var c=g.ql(this.element,this.element.parentElement);this.Ib=a-c.x;this.vc=b-c.y};
g.k.zQ=function(a,b){if(a!==this.vb||b!==this.Cb){g.Ll(this.element,"ytp-dragging")||g.Ml(this.element,"ytp-dragging");var c=g.ul(this.element);a=a-this.Ib-.02*this.playerWidth;var d=b-this.vc-.02*this.playerHeight,e=(a+c.width/2)/this.maxWidth*3;e=Math.floor(g.Ed(e,0,2));var f=(d+c.height/2)/this.Xa*3;f=Math.floor(g.Ed(f,0,2));b=e+3*f;a=(a+e/2*c.width)/this.maxWidth;a=100*g.Ed(a,0,1);c=(d+f/2*c.height)/this.Xa;c=100*g.Ed(c,0,1);this.u.params.lh=b;this.u.params.Pi=c;this.u.params.Cg=a;this.u.params.isDefault=
!1;this.j.lh=b;this.j.Pi=c;this.j.Cg=a;this.j.isDefault=!1;this.ea.lh=b;this.ea.Pi=c;this.ea.Cg=a;this.ea.isDefault=!1;this.rL()}};
g.k.yQ=function(){g.Ol(this.element,"ytp-dragging")};
g.k.rL=function(){this.ws(this.G)};
g.k.getType=function(){return this.type};
g.k.ws=function(a){var b=Math.min(this.QI(),this.maxWidth),c=this.OI(),d="";3===this.u.params.kf&&(d="rotate(180deg)");g.il(this.element,{top:0,left:0,right:"",bottom:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"96%","max-height":"96%",margin:"",transform:""});this.tB(a);d={transform:d,top:"",left:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"","max-height":""};var e=.96*this.j.Cg+2,f=this.j.lh;switch(f){case 0:case 3:case 6:(b=this.j.Uc.fontSizeIncrement)&&0<b&&2!==this.j.kf&&3!==
this.j.kf&&(e=Math.max(e/(1+2*b),2));d.left=e+"%";break;case 1:case 4:case 7:d.left=e+"%";e=this.D.offsetWidth;b||e?(b=b||e+1,d.width=b+"px",d["margin-left"]=b/-2+"px"):d.transform+=" translateX(-50%)";break;case 2:case 5:case 8:d.right=100-e+"%"}b=.96*this.j.Pi+2;switch(f){case 0:case 1:case 2:d.top=b+"%";break;case 3:case 4:case 5:d.top=b+"%";(c=c||this.element.clientHeight)?(d.height=c+"px",d["margin-top"]=c/-2+"px"):d.transform+=" translateY(-50%)";break;case 6:case 7:case 8:d.bottom=100-b+"%"}g.il(this.element,
d);if(this.F){c=this.D.offsetHeight;d=1;for(f=0;f<a.length;f++)b=a[f],"string"===typeof b.text&&(d+=b.text.split("\n").length-1,b.append||0===f||d++);a=c/d;this.F.style.height=a+"px";this.F.style.width=a+"px";this.element.style.paddingLeft=a+5+"px";this.element.style.paddingRight=a+5+"px";this.element.style.marginLeft="-"+(a+5)+"px";this.element.style.marginRight="-"+(a+5)+"px"}};
g.k.tB=function(a){var b;for(b=0;b<a.length&&a[b]===this.G[b];b++);if(this.Ba||this.G.length>b)b=0,this.Ba=!1,this.G=[],this.K=this.Fa=this.Aa=null,g.he(this.D);for(;b<a.length;b++)rJa(this,a[b])};
g.k.QI=function(){return 0};
g.k.OI=function(){return 0};
g.k.toString=function(){return g.oL.prototype.toString.call(this)};g.y(h6,V5);h6.prototype.Fv=function(a,b,c){RIa(this.videoData.videoId,a.vssId,c)};
h6.prototype.Gv=function(a){if(this.audioTrack)for(var b=g.v(this.audioTrack.captionTracks),c=b.next();!c.done;c=b.next())U5(this.u,c.value);a()};g.y(i6,g6);i6.prototype.tB=function(a){var b=this.u.j;g6.prototype.tB.call(this,a);for(a=a.length;a<b.length;a++){var c=b[a];if(f&&c.j===e)var d=f;else{d={};Object.assign(d,c.j);Object.assign(d,kKa);var e=c.j;var f=d}rJa(this,c,d)}};
var kKa={hP:!0};g.y(j6,g6);g.k=j6.prototype;g.k.rL=function(){g.Gl(this.Wa)};
g.k.ZQ=function(){g.Ol(this.element,"ytp-rollup-mode");this.ws(this.Rc,!0)};
g.k.OI=function(){return this.C?this.ma:this.V};
g.k.QI=function(){return this.C?this.V:this.ma};
g.k.ws=function(a,b){this.Rc=a;if(this.u.params.rl){for(var c=0,d=0;d<this.G.length&&c<a.length;d++)this.G[d]===a[c]&&c++;0<c&&c<a.length&&(a=this.G.concat(a.slice(c)));this.Qb=this.ma;this.V=this.ma=0;g6.prototype.ws.call(this,a);uJa(this,b)}g6.prototype.ws.call(this,a)};g.y(k6,g.IK);k6.prototype.toString=function(){return g.IK.prototype.toString.call(this)};g.y(l6,g.IK);l6.prototype.toString=function(){return g.IK.prototype.toString.call(this)};
var m6=0;g.y(n6,g.F);n6.prototype.u=function(){return[]};
n6.prototype.reset=function(){};g.y(o6,n6);o6.prototype.reset=function(){this.G={};this.B=this.j=null;this.F=!0};
o6.prototype.u=function(a,b){a=a.firstChild;a.getAttribute("format");b=b||0;Number.isFinite(b);a=Array.from(a.childNodes);a=g.v(a);for(var c=a.next();!c.done;c=a.next())if(c=c.value,1===c.nodeType)switch(c.tagName){case "head":var d=c;break;case "body":var e=c}if(d)for(d=Array.from(d.childNodes),d=g.v(d),a=d.next();!a.done;a=d.next())if(a=a.value,1===a.nodeType)switch(a.tagName){case "pen":c=a.getAttribute("id");var f=this.pens,h={},l=a.getAttribute("p");l&&Object.assign(h,this.pens[l]);l=q6(a,"b");
null!=l&&(h.bold=l);l=q6(a,"i");null!=l&&(h.italic=l);l=q6(a,"u");null!=l&&(h.underline=l);l=r6(a,"et");null!=l&&(h.charEdgeStyle=l);l=r6(a,"of");null!=l&&(h.offset=l);l=t6(a,"bc");null!=l&&(h.background=l);l=t6(a,"ec");null!=l&&(h.IB=l);l=t6(a,"fc");null!=l&&(h.color=l);l=r6(a,"fs");null!=l&&0!==l&&(h.fontFamily=l);l=p6(a,"sz");void 0!==l&&(h.fontSizeIncrement=l/100-1);l=p6(a,"bo");void 0!==l&&(h.backgroundOpacity=l/255);l=p6(a,"fo");void 0!==l&&(h.textOpacity=l/255);l=r6(a,"rb");null!=l&&10!==l&&
0!==l&&(h.Od=10<l?l-1:l);a=r6(a,"hg");null!=a&&(h.oJ=a);f[c]=h;break;case "ws":c=a.getAttribute("id");this.T[c]=yJa(this,a);break;case "wp":c=a.getAttribute("id"),this.K[c]=zJa(this,a)}if(e){d=[];e=Array.from(e.childNodes);e=g.v(e);for(a=e.next();!a.done;a=e.next())if(a=a.value,1===a.nodeType)switch(a.tagName){case "w":this.j=AJa(this,a,b,!1);(a=this.G[this.j.id])&&a.end>this.j.start&&(a.end=this.j.start);this.G[this.j.id]=this.j;d.push(this.j);break;case "p":l=b;c=[];f=a.getAttribute("w")||this.D;
h=!!q6(a,"a");l=(p6(a,"t")||0)+l;var m=p6(a,"d")||5E3;h||(!this.F&&this.B&&this.B.windowId===f&&this.B.end>l&&(this.B.end=l),this.B&&"\n"===this.B.text&&(this.B.text=""));var n=h?6:5,p=a.getAttribute("p");p=p?this.pens[p]:null;var q=Array.from(a.childNodes);q.length&&(this.F=null!=a.getAttribute("d"));for(var r=0;r<q.length;r++){var t=q[r],u=void 0;0<r&&(h=!0);var x=void 0;1===t.nodeType&&(x=t);if(x&&"s"===x.tagName){if((t=(t=x.getAttribute("p"))?this.pens[t]:null)&&t.Od&&(1===t.Od?(t=q.slice(r,r+
4),4===t.length&&(u=xJa(l,m,f,h,n,t,this.pens),r+=3)):u=xJa(l,m,f,h,n,[x],this.pens)),!u){var A=x;u=l;x=m;t=f;var B=h,C=n,G=A.textContent?A.textContent:"",O=A.getAttribute("p");O=O?this.pens[O]:null;A=p6(A,"t")||0;u=new k6(u+A,x-A,C,t,G,B,O)}}else u=new k6(l,m,n,f,t.textContent||"",h,p);c.push(u);this.B=u}if(0<c.length)for(c[0].windowId===this.D&&(this.j=AJa(this,a,b,!0),d.push(this.j)),a=g.v(c),c=a.next();!c.done;c=a.next())c=c.value,c.windowId=this.j.id,this.j.j.push(c),d.push(c)}b=d}else b=[];
return b};var lKa=new Map([[9,1],[10,1],[11,2],[12,3],[13,4],[14,5]]);g.y(u6,n6);u6.prototype.reset=function(){this.B.clear()};
u6.prototype.u=function(a,b){var c=JSON.parse(a);if(!c)return[];if(c.pens){a=0;for(var d=g.v(c.pens),e=d.next();!e.done;e=d.next()){e=e.value;var f={},h=e.pParentId;h&&Object.assign(f,this.j.get(h));e.bAttr&&(f.bold=!0);e.iAttr&&(f.italic=!0);e.uAttr&&(f.underline=!0);h=e.ofOffset;null!=h&&(f.offset=h);void 0!==e.szPenSize&&(f.fontSizeIncrement=e.szPenSize/100-1);h=e.etEdgeType;null!=h&&(f.charEdgeStyle=h);void 0!==e.ecEdgeColor&&(f.IB=v6(e.ecEdgeColor));h=e.fsFontStyle;null!=h&&0!==h&&(f.fontFamily=
h);void 0!==e.fcForeColor&&(f.color=v6(e.fcForeColor));void 0!==e.foForeAlpha&&(f.textOpacity=e.foForeAlpha/255);void 0!==e.bcBackColor&&(f.background=v6(e.bcBackColor));void 0!==e.boBackAlpha&&(f.backgroundOpacity=e.boBackAlpha/255);(h=e.rbRuby)&&10!==h&&(f.Od=10<h?h-1:h,f.Oi=lKa.get(f.Od));e.hgHorizGroup&&(f.oJ=e.hgHorizGroup);this.j.set(a++,f)}}if(c.wsWinStyles)for(a=0,d=g.v(c.wsWinStyles),e=d.next();!e.done;e=d.next())e=e.value,f={},(h=e.wsParentId)?Object.assign(f,this.D.get(h)):Object.assign(f,
this.F),void 0!==e.mhModeHint&&(f.Gr=e.mhModeHint),void 0!==e.juJustifCode&&(f.textAlign=e.juJustifCode),void 0!==e.pdPrintDir&&(f.kf=e.pdPrintDir),void 0!==e.sdScrollDir&&(f.DF=e.sdScrollDir),void 0!==e.wfcWinFillColor&&(f.windowColor=v6(e.wfcWinFillColor)),void 0!==e.wfoWinFillAlpha&&(f.windowOpacity=e.wfoWinFillAlpha/255),this.D.set(a++,f);if(c.wpWinPositions)for(a=0,d=g.v(c.wpWinPositions),e=d.next();!e.done;e=d.next())e=e.value,f={},(h=e.wpParentId)&&Object.assign(f,this.C.get(h)),void 0!==e.ahHorPos&&
(f.Cg=e.ahHorPos),void 0!==e.apPoint&&(f.lh=e.apPoint),void 0!==e.avVerPos&&(f.Pi=e.avVerPos),void 0!==e.ccCols&&(f.Yl=e.ccCols),void 0!==e.rcRows&&(f.rl=e.rcRows),this.C.set(a++,f);if(c.events){a=[];c=g.v(c.events);for(d=c.next();!d.done;d=c.next()){var l=d.value;d=(l.tStartMs||0)+b;e=l.dDurationMs||0;if(l.id)f=String(l.id),d=BJa(this,l,d,e,f),a.push(d),this.B.set(f,d);else{l.wWinId?f=l.wWinId.toString():(f="_"+m6++,h=BJa(this,l,d,e,f),a.push(h),this.B.set(f,h));0===e&&(e=5E3);h=this.B.get(f);var m=
!!l.aAppend,n=m?6:5,p=l.segs,q=null;l.pPenId&&(q=this.j.get(l.pPenId));for(l=0;l<p.length;l++){var r=p[l],t=r.utf8;if(t){var u=r.tOffsetMs||0,x=null;r.pPenId&&(x=this.j.get(r.pPenId));if(2===(null!=h.params.Gr?h.params.Gr:1<h.j.length?1:0)&&m&&"\n"===t)continue;if(r=x&&1===x.Od)if(r=l,r+3>=p.length||!p[r+1].pPenId||!p[r+2].pPenId||!p[r+3].pPenId)r=!1;else{var A=p[r+1].pPenId;(A=this.j.get(A))&&A.Od&&2===A.Od?(A=p[r+2].pPenId,A=this.j.get(A),!A||!A.Od||3>A.Od?r=!1:(A=p[r+3].pPenId,r=(A=this.j.get(A))&&
A.Od&&2===A.Od?!0:!1)):r=!1}if(r){u=p[l+1].utf8;r=p[l+3].utf8;A=p[l+2].utf8;var B=this.j.get(p[l+2].pPenId);t=wJa(t,u,A,r,B);m=new k6(d,e,n,f,t,m,x);l+=3}else m=new k6(d+u,e-u,n,h.id,t,m,x||q);m&&(a.push(m),h.j.push(m))}m=!0}}}b=a}else b=[];return b};x6.prototype.clear=function(){this.B=this.time=this.mode=0;this.j=[];this.reset()};
x6.prototype.reset=function(){this.mode=0;this.C.reset(0);this.D.reset(1)};
var CJa=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];y6.prototype.set=function(a){this.type=a};
y6.prototype.get=function(){return this.type};
z6.prototype.clear=function(){this.state=0};
z6.prototype.update=function(){this.state=2===this.state?1:0};
z6.prototype.isValid=function(){return 0!==this.state};
z6.prototype.matches=function(a,b){return this.isValid()&&a===this.Yn&&b===this.Vl};
HJa.prototype.reset=function(){this.timestamp=this.j=0};
A6.prototype.updateTime=function(a){for(var b=1;15>=b;++b)for(var c=1;32>=c;++c)this.B[b][c].timestamp=a};
A6.prototype.debugString=function(){for(var a="\n",b=1;15>=b;++b){for(var c=1;32>=c;++c){var d=this.B[b][c];a=0===d.j?a+"_":a+String.fromCharCode(d.j)}a+="\n"}return a};
A6.prototype.reset=function(a){for(var b=0;15>=b;b++)for(var c=0;32>=c;c++)this.B[b][c].reset();this.C=a;this.j=0;this.u=this.row=1};
var IJa=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],JJa=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],KJa=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],LJa=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];G6.prototype.reset=function(a,b){this.D=b;this.style.set(2);this.u=this.F;this.C=this.G;this.j=this.u;var c=(a<<2)+(b<<1);this.F.reset(c);this.G.reset(c);this.text.reset((a<<2)+(b<<1)+1)};
w6.prototype.reset=function(a){this.D=a;this.u.clear();this.C=this.B;this.B.reset(a,0);this.F.reset(a,1)};QJa.prototype.C=function(){};g.y(I6,QJa);I6.prototype.C=function(a,b,c,d,e){if(c<d){var f="_"+m6++;c=c/1E3-this.F;d=d/1E3-this.F;a=new l6(c,d-c,5,f,{textAlign:0,lh:0,Cg:2.5*b,Pi:5.33*a});e=new k6(c,d-c,5,f,e);this.u.push(a);this.u.push(e)}};
g.y(L6,n6);L6.prototype.u=function(a){a=new I6(a,a.byteLength,this.B);if(RJa(a)){for(;a.byteOffset<a.j.byteLength;)for(0===a.version?a.B=K6(a)*(1E3/45):1===a.version&&(a.B=4294967296*K6(a)+K6(a)),a.D=J6(a);0<a.D;a.D--){var b=J6(a),c=J6(a),d=J6(a);b&4&&(b&3)===this.track&&(0===this.track||1===this.track)&&(b=this.j,b.j.push({time:a.B,type:this.track,UH:c,VH:d,order:b.j.length}))}GJa(this.j,a);return a.u}return[]};
L6.prototype.reset=function(){this.j.clear()};g.y(N6,n6);
N6.prototype.u=function(a,b){var c=[];a=a.split(mKa);for(var d=1;d<a.length;d++){var e=a[d],f=b;if(""!==e&&!nKa.test(e)){var h=F$.exec(e);if(h&&4<=h.length){var l=O6(h[1]),m=O6(h[2])-l;l+=f;var n=(h=h[3])?h.split(" "):[];h={};var p=null;var q="";var r=null,t="";n=g.v(n);for(var u=n.next();!u.done;u=n.next())if(u=u.value.split(":"),2===u.length){var x=u[1];switch(u[0]){case "line":u=x.split(",");u[0].endsWith("%")&&(p=u[0],h.Pi=Number.parseInt(p,10),2===u.length&&(q=u[1].trim()));break;case "position":u=
x.split(",");r=u[0];h.Cg=Number.parseInt(r,10);2===u.length&&(t=u[1].trim());break;case "align":switch(x){case "start":h.textAlign=0;break;case "middle":h.textAlign=2;break;case "end":h.textAlign=1}}}p||q||(q="end");if(!r)switch(h.textAlign){case 0:h.Cg=0;break;case 1:h.Cg=100;break;case 2:h.Cg=50}if(null!=h.textAlign){p=0;switch(q){case "center":p+=3;break;case "end":p+=6;break;default:p+=0}switch(t){case "line-left":p+=0;break;case "center":p+=1;break;case "line-right":p+=2;break;default:switch(h.textAlign){case 0:p+=
0;break;case 2:p+=1;break;case 1:p+=2}}q=0>p||8<p?7:p;h.lh=q}e=e.substring(F$.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");t=h;h=e;e={};if(0>h.indexOf("<")&&0>h.indexOf("&"))f=TJa(l,m,5,t),m=new k6(l,m,5,f.id,h,!1,g.zc(e)?void 0:e),c.push(f),c.push(m),f.j.push(m);else for(q=h.split(oKa),1===q.length?(h=5,t=TJa(l,m,h,t)):(p=h=6,t=Object.assign({Yl:32},t),t=new l6(l,m,p,"_"+m6++,t)),c.push(t),p=l,r=0;r<q.length;r++)n=q[r],0===r%2?(u=iJa("<html>"+n+"</html>"),u.getElementsByTagName("parsererror").length?
(x=u.createElement("span"),x.appendChild(u.createTextNode(n))):x=u.firstChild,SJa(this,p,m-(p-l),h,t,0<r,x,e,c)):p=O6(n)+f}F$.lastIndex=0}}return c};
var nKa=/^NOTE/,mKa=/(?:\r\n|\r|\n){2,}/,F$=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),oKa=RegExp("<((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})>");g.UM.Vq(N6,{u:"wvppt"});g.y(P6,g.F);P6.prototype.clear=function(){this.parser&&this.parser.dispose();this.parser=null};
P6.prototype.reset=function(){this.parser&&this.parser.reset()};
P6.prototype.va=function(){g.F.prototype.va.call(this);this.clear()};var h$={windowColor:"#080808",windowOpacity:0,textAlign:2,lh:7,Cg:50,Pi:100,isDefault:!0,Uc:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.y(R6,g.PL);g.k=R6.prototype;g.k.va=function(){if(this.C||this.ma){var a=this.N.Vc();a&&!a.isDisposed()&&a.lq()}else j$(this,!1);g.PL.prototype.va.call(this)};
g.k.mF=function(){if(this.Na)return this.C||this.ma;var a=N5(this.player.getAudioTrack(),g.hI(this.J));return"CAPTIONS_INITIAL_STATE_ON_REQUIRED"===a?!0:"CAPTIONS_INITIAL_STATE_OFF_REQUIRED"===a?T6(this):S6(this)||T6(this)?!0:dKa(this)};
g.k.load=function(){var a=this;g.PL.prototype.load.call(this);this.F=this.player.getAudioTrack();this.u?this.j&&(this.Wa.clear(),this.C?gKa(this,!0):3!==this.player.getPresentingPlayerType()&&this.u.Fv(this.j,"json3",function(b,c,d,e){if(b){a.u.XK()&&(a.Ba=[],a.N.Pj("captions"),R5(a.Aa),a.Wa.reset());b=ZJa(a.Wa,b,c,d,e);a.player.Rg(b,void 0,a.fb);if(!(!a.ea||a.ma||W6(a)||g.VH(a.J)||g.WH(a.J)||g.NH(a.J)||"shortspage"===a.J.F||a.player.isInline())){b=a.Ga;b.isActive()&&g.Gl(b);b=vJa({lh:0,Cg:5,Pi:5,
rl:2,textAlign:0,kf:0,lang:"en"});a.Fa=[b];d=["Click "," for settings"];a.Xa||(e=new g.lL({S:"svg",Ka:{height:"100%",version:"1.1",viewBox:"0 0 36 36",width:"100%"},Da:[{S:"path",BF:!0,Ka:{d:"m 23.94,18.78 c .03,-0.25 .05,-0.51 .05,-0.78 0,-0.27 -0.02,-0.52 -0.05,-0.78 l 1.68,-1.32 c .15,-0.12 .19,-0.33 .09,-0.51 l -1.6,-2.76 c -0.09,-0.17 -0.31,-0.24 -0.48,-0.17 l -1.99,.8 c -0.41,-0.32 -0.86,-0.58 -1.35,-0.78 l -0.30,-2.12 c -0.02,-0.19 -0.19,-0.33 -0.39,-0.33 l -3.2,0 c -0.2,0 -0.36,.14 -0.39,.33 l -0.30,2.12 c -0.48,.2 -0.93,.47 -1.35,.78 l -1.99,-0.8 c -0.18,-0.07 -0.39,0 -0.48,.17 l -1.6,2.76 c -0.10,.17 -0.05,.39 .09,.51 l 1.68,1.32 c -0.03,.25 -0.05,.52 -0.05,.78 0,.26 .02,.52 .05,.78 l -1.68,1.32 c -0.15,.12 -0.19,.33 -0.09,.51 l 1.6,2.76 c .09,.17 .31,.24 .48,.17 l 1.99,-0.8 c .41,.32 .86,.58 1.35,.78 l .30,2.12 c .02,.19 .19,.33 .39,.33 l 3.2,0 c .2,0 .36,-0.14 .39,-0.33 l .30,-2.12 c .48,-0.2 .93,-0.47 1.35,-0.78 l 1.99,.8 c .18,.07 .39,0 .48,-0.17 l 1.6,-2.76 c .09,-0.17 .05,-0.39 -0.09,-0.51 l -1.68,-1.32 0,0 z m -5.94,2.01 c -1.54,0 -2.8,-1.25 -2.8,-2.8 0,-1.54 1.25,-2.8 2.8,-2.8 1.54,0 2.8,1.25 2.8,2.8 0,1.54 -1.25,2.8 -2.8,2.8 l 0,0 z",
fill:"#fff"}}]}),g.H(a,e),a.Xa=e.element);e=b.end-b.start;var f=g.BI(a.j);f&&a.Fa.push(new k6(b.start,e,0,b.id,f));a.Fa.push(new k6(b.start,e,0,b.id,d[0]),new k6(b.start,e,0,b.id,a.Xa,!0),new k6(b.start,e,0,b.id,d[1],!0));a.player.Rg(a.Fa);g.Fl(a.Ga)}!a.ea||a.ma||W6(a)||(g.hI(a.J)?c$(a,!0):d$(a,!0),a.F&&(a.F.C=a.j),a.player.Lp());var h;null==(h=a.N.Rb())||h.Y("cc",{kind:c.kind});a.ea=!1}}),this.C||this.ma||W6(this)||this.player.Ia("captionschanged",O5(this.j))):(this.u=eKa(this),g.H(this,this.u),
this.u.Gv(function(){fKa(a)}))};
g.k.unload=function(){if(this.C&&this.j)gKa(this,!1);else{if(this.Ga){var a=this.Ga;a.isActive()&&g.Gl(a)}this.player.Pj("captions");this.Ba=[];this.u&&this.u.Dl();this.Wa.clear();this.G&&this.player.Rg(this.G);this.RF()}g.PL.prototype.unload.call(this);this.player.Lp();this.player.Ia("captionschanged",{})};
g.k.create=function(){this.mF()&&this.load();var a;a:{var b,c,d;if(this.J.I("suggest_caption_correction_menu_item")&&this.J.I("web_player_nitrate_promo_tooltip")&&(null==(b=this.videoData.getPlayerResponse())?0:null==(c=b.captions)?0:null==(d=c.playerCaptionsTracklistRenderer)?0:d.openTranscriptCommand)){var e,f;if(b=null==(a=this.videoData.getPlayerResponse())?void 0:null==(e=a.captions)?void 0:null==(f=e.playerCaptionsTracklistRenderer)?void 0:f.captionTracks)for(a=g.v(b),e=a.next();!e.done;e=a.next())if(e=
e.value,"asr"===e.kind&&"en"===e.languageCode){a=!0;break a}}a=!1}a&&this.N.Z("showpromotooltip",this.K.element)};
g.k.rR=function(){for(var a=this.N.Vc().Zc().textTracks,b=null,c=0;c<a.length;c++)if("showing"===a[c].mode)a:{b=a[c].id;for(var d=T5(this.u.u,!0),e=0;e<d.length;e++)if(d[e].toString()===b){b=d[e];break a}b=null}(this.loaded?this.j:null)!==b&&X6(this,b,!0)};
g.k.NS=function(){!this.j&&this.C||this.unload()};
g.k.onCueRangeEnter=function(a){this.Ba.push(a);R5(this.Aa)};
g.k.onCueRangeExit=function(a){g.pb(this.Ba,a);this.u instanceof Z5&&this.u.F&&this.player.jf([a]);R5(this.Aa)};
g.k.getCaptionWindowContainerId=function(){return this.K.element.id};
g.k.UR=function(){jKa(this,this.Fa);this.Fa=null};
g.k.PF=function(){var a=this;if(!this.Cb||!this.C){this.Aa.stop();g.Ac(this.Ha);this.Ba.sort(g.KK);var b=this.Ba;if(this.G){var c=g.Xy(b,function(f){return-1===this.G.indexOf(f)},this);
c.length&&(b=c)}b=g.v(b);for(c=b.next();!c.done;c=b.next())iKa(this,c.value);b={};c=g.v(Object.entries(this.V));for(var d=c.next();!d.done;b={Dn:b.Dn,Rh:b.Rh},d=c.next()){var e=g.v(d.value);d=e.next().value;e=e.next().value;b.Dn=d;b.Rh=e;this.Ha[b.Dn]?(b.Rh.element.parentNode||(b.Rh instanceof j6||b.Rh instanceof i6||g.pc(this.V,function(f){return function(h,l){l!==f.Dn&&h.u.params.lh===f.Rh.u.params.lh&&h.u.params.Cg===f.Rh.u.params.Cg&&h.u.params.Pi===f.Rh.u.params.Pi&&(h.dispose(),delete a.V[l]);
return l===f.Dn}}(b),this),this.K.element.appendChild(b.Rh.element)),b.Rh.ws(this.Ha[b.Dn])):(b.Rh.dispose(),delete this.V[b.Dn])}}};
g.k.ZR=function(){Q6(this,{},!0);this.player.Ia("captionssettingschanged")};
g.k.HO=function(){var a=h$.Uc;a={background:a.background,backgroundOpacity:a.backgroundOpacity,charEdgeStyle:a.charEdgeStyle,color:a.color,fontFamily:a.fontFamily,fontSizeIncrement:a.fontSizeIncrement,fontStyle:a.bold&&a.italic?3:a.bold?1:a.italic?2:0,textOpacity:a.textOpacity,windowColor:h$.windowColor,windowOpacity:h$.windowOpacity};var b=S5()||{};null!=b.background&&(a.background=b.background);null!=b.backgroundOverride&&(a.backgroundOverride=b.backgroundOverride);null!=b.backgroundOpacity&&(a.backgroundOpacity=
b.backgroundOpacity);null!=b.backgroundOpacityOverride&&(a.backgroundOpacityOverride=b.backgroundOpacityOverride);null!=b.charEdgeStyle&&(a.charEdgeStyle=b.charEdgeStyle);null!=b.charEdgeStyleOverride&&(a.charEdgeStyleOverride=b.charEdgeStyleOverride);null!=b.color&&(a.color=b.color);null!=b.colorOverride&&(a.colorOverride=b.colorOverride);null!=b.fontFamily&&(a.fontFamily=b.fontFamily);null!=b.fontFamilyOverride&&(a.fontFamilyOverride=b.fontFamilyOverride);null!=b.fontSizeIncrement&&(a.fontSizeIncrement=
b.fontSizeIncrement);null!=b.fontSizeIncrementOverride&&(a.fontSizeIncrementOverride=b.fontSizeIncrementOverride);null!=b.fontStyle&&(a.fontStyle=b.fontStyle);null!=b.fontStyleOverride&&(a.fontStyleOverride=b.fontStyleOverride);null!=b.textOpacity&&(a.textOpacity=b.textOpacity);null!=b.textOpacityOverride&&(a.textOpacityOverride=b.textOpacityOverride);null!=b.windowColor&&(a.windowColor=b.windowColor);null!=b.windowColorOverride&&(a.windowColorOverride=b.windowColorOverride);null!=b.windowOpacity&&
(a.windowOpacity=b.windowOpacity);null!=b.windowOpacityOverride&&(a.windowOpacityOverride=b.windowOpacityOverride);return a};
g.k.jM=function(a,b){var c={};Object.assign(c,S5());Object.assign(c,a);Q6(this,c,b);this.player.Ia("captionssettingschanged")};
g.k.RF=function(){!this.C&&this.loaded&&(g.mc(this.V,function(a,b){a.dispose();delete this.V[b]},this),this.PF())};
g.k.hk=function(a,b){switch(a){case "fontSize":if(isNaN(b))break;var c=g.Ed(b,-2,4);this.jM({fontSizeIncrement:c});return c;case "reload":b&&!this.C&&X6(this,this.j,!0);break;case "stickyLoading":void 0!==b&&this.J.B&&(g.hI(this.J)?c$(this,!!b):d$(this,!!b));break;case "track":if(!this.u)return{};if(b){if(this.C)break;if(!g.Ma(b))break;if(g.zc(b)){X6(this,null,!0);break}a=T5(this.u.u,!0);for(var d=0;d<a.length;d++){var e=a[d];e.languageCode!==b.languageCode||c&&e.languageName!==b.languageName||(c=
b.translationLanguage?PIa(e,b.translationLanguage):e)}this.jA(b.position);!c||c===this.j&&this.loaded||(b=g.KB(),a=P5(c),b.length&&a===b[b.length-1]||(b.push(a),g.qx("yt-player-caption-language-preferences",b)),OIa(this.J)&&!this.N.isInline()&&g.qx("yt-player-caption-sticky-language",a),X6(this,c,!0))}else return this.loaded&&this.j&&!W6(this)?O5(this.j):{};return"";case "tracklist":return this.u?g.Gg(T5(this.u.u,!(!b||!b.includeAsr)),function(f){return O5(f)}):[];
case "translationLanguages":return this.u?this.u.C.map(function(f){return Object.assign({},f)}):[];
case "sampleSubtitles":this.C||void 0===b||j$(this,!!b);break;case "sampleSubtitlesCustomized":this.C||j$(this,!!b,b)}};
g.k.getOptions=function(){var a="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.J.B&&a.push("stickyLoading");return a};
g.k.Dk=function(){var a=this.j;if(a){var b=a.vssId;a.translationLanguage&&b&&(b="t"+b+"."+P5(a));return{cc:b}}return{}};
g.k.FS=function(){this.isSubtitlesOn()?(g.hI(this.J)?c$(this,!1):d$(this,!1),this.unload(),T6(this,!0)&&X6(this,U6(this),!1)):this.WL()};
g.k.WL=function(){this.isSubtitlesOn()||X6(this,W6(this)||!this.j?V6(this,!0):this.j,!0)};
g.k.isSubtitlesOn=function(){return!!this.loaded&&!!this.j&&!W6(this)};
g.k.sQ=function(){var a=W6(this);T6(this,a)?X6(this,this.player.getAudioTrack().u,!1):this.videoData.captionTracks.length&&(this.loaded&&this.unload(),this.mF()&&(a?X6(this,V6(this),!1):this.load()))};
g.k.jA=function(a){a&&(this.T={top:a.top,right:a.right,bottom:a.bottom,left:a.left,width:1-a.left-a.right,height:1-a.top-a.bottom},this.K.element.style.top=100*this.T.top+"%",this.K.element.style.left=100*this.T.left+"%",this.K.element.style.width=100*this.T.width+"%",this.K.element.style.height=100*this.T.height+"%")};
g.k.GQ=function(){var a=this.N.Vc();a&&!a.isDisposed()&&a.lq();this.N.isFullscreen()?(this.C=this.Na=!0,this.loaded&&fKa(this)):(this.Na="3"===this.J.controlsType,this.C=bKa(this));X6(this,this.j)};
g.k.RA=function(){var a,b,c,d=null==(a=this.videoData.getPlayerResponse())?void 0:null==(b=a.captions)?void 0:null==(c=b.playerCaptionsTracklistRenderer)?void 0:c.openTranscriptCommand;d&&this.player.Ia("innertubeCommand",d)};
g.UM.Vq(R6,{PF:"smucd"});g.OL("captions",R6);})(_yt_player);
